Repository keyshade-xyz/keyshade, pull requests merged in 2023-12, with the labels that each got.

#7 update license to MPL-2.0
  package.json
Labels: enhancement

#24 Update README.md
  README.md
Labels: documentation

#25 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#32 feat: husky configured
  .husky/pre-commit
  package.json
Labels: enhancement

#44 build(cli): Add lint workflow for API
  .github/workflows/api.yaml
Labels: enhancement

#43 chore: add `getAllUsers` test
  apps/api/src/common/mock-data/users.ts
  apps/api/src/user/fake.repository.ts
  apps/api/src/user/user.controller.spec.ts
  apps/api/src/user/user.service.spec.ts
Labels: Tests

#47 feat: responsive landing
  apps/web/app/page.tsx
  apps/web/components/Links.tsx
Labels: enhancement

#37 feat: invalidate older OTPs
  apps/api/src/auth/admin.guard.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.guard.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/decorators/user.decorator.ts
  apps/api/src/main.ts
  apps/api/src/prisma/prisma.repository.ts
  apps/api/src/resend/services/mail.resend.ts
  apps/api/src/user/dto/update.user/update.user.spec.ts
  apps/api/src/user/dto/update.user/update.user.ts
  apps/api/tsconfig.spec.json
Labels: enhancement, bug_fix
