Repository keyshade-xyz/keyshade, pull requests merged in 2024-11, with the labels that each got.

#489 feat(platform): Create ui link for resend otp
  apps/platform/.eslintrc.cjs
  apps/platform/.eslintrc.js
  apps/platform/src/app/auth/otp/page.tsx
  apps/platform/src/lib/controller-instance.ts
  packages/api-client/src/controllers/auth.ts
  packages/api-client/src/index.ts
  packages/api-client/src/types/auth.types.ts
  packages/api-client/src/types/index.types.ts
Labels: enhancement, Review effort [1-5]: 2, hacktoberfest-accepted

#520 refactor(api-client, schema): Add workspace's schemas and types in @keyshade/schema
  packages/api-client/package.json
  packages/api-client/src/controllers/workspace.ts
  packages/api-client/src/types/workspace.types.d.ts
  packages/schema/package.json
  packages/schema/src/api-key.ts
  packages/schema/src/index.ts
  packages/schema/src/integration.ts
  packages/schema/src/pagination/pagination.ts
  packages/schema/src/pagination/pagination.types.ts
  packages/schema/src/project.ts
  packages/schema/src/secret.ts
  packages/schema/src/workspace-role.ts
  packages/schema/src/workspace.ts
  packages/schema/src/workspace/workspace.ts
  packages/schema/src/workspace/workspace.types.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/environment.spec.ts
  packages/schema/tests/integration.spec.ts
  packages/schema/tests/pagination.spec.ts
  packages/schema/tests/project.spec.ts
  packages/schema/tests/secret.spec.ts
  packages/schema/tests/variable.spec.ts
  packages/schema/tests/workspace-role.spec.ts
  packages/schema/tests/workspace.spec.ts
  packages/schema/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort [1-5]: 4

#532 feat(schema, api-client): Migrate auth types to @keyshade/schema
  packages/api-client/src/controllers/auth.ts
  packages/api-client/src/controllers/environment.ts
  packages/api-client/src/controllers/event.ts
  packages/api-client/src/controllers/integration.ts
  packages/api-client/src/controllers/project.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/user.ts
  packages/api-client/src/controllers/variable.ts
  packages/api-client/src/controllers/workspace-membership.ts
  packages/api-client/src/controllers/workspace-role.ts
  packages/api-client/src/core/pagination-parser.ts
  packages/api-client/src/core/response-parser.ts
  packages/api-client/src/types/auth.types.ts
  packages/api-client/src/types/environment.types.d.ts
  packages/api-client/src/types/event.types.d.ts
  packages/api-client/src/types/index.types.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/api-client/src/types/project.types.d.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/api-client/src/types/user.types.d.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/tsconfig.json
  packages/schema/package.json
  packages/schema/src/auth/auth.ts
  packages/schema/src/auth/auth.types.ts
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/workspace/workspace.ts
  packages/schema/tests/auth.spec.ts
  packages/schema/tests/workspace.spec.ts
Labels: Review effort [1-5]: 2

#534 test(secret-scan): Add test coverage
  .github/workflows/validate-secret-scan.yaml
  codecov.yml
  packages/secret-scan/.mocharc.json
  packages/secret-scan/jest.config.ts
  packages/secret-scan/package.json
  packages/secret-scan/src/test/secret.test.ts
  packages/secret-scan/tsconfig.json
  packages/secret-scan/tsconfig.spec.json
  pnpm-lock.yaml
Labels: Review effort [1-5]: 2

#536 feat(cli): Store `metrics_enabled` key in profile config
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/profile/create.profile.ts
  apps/cli/src/commands/profile/list.profile.ts
  apps/cli/src/commands/profile/update.profile.ts
  apps/cli/src/types/index.types.d.ts
Labels: Review effort [1-5]: 2

#538 feat(schema, api-client): Migrate project schemas and environment schemas along with their types to @keyshade/schema
  packages/api-client/src/controllers/environment.ts
  packages/api-client/src/controllers/project.ts
  packages/api-client/src/types/environment.types.d.ts
  packages/api-client/src/types/project.types.d.ts
  packages/schema/src/environment.ts
  packages/schema/src/environment/index.ts
  packages/schema/src/environment/index.types.ts
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/project.ts
  packages/schema/src/project/index.ts
  packages/schema/src/project/index.types.ts
  packages/schema/tests/environment.spec.ts
  packages/schema/tests/project.spec.ts
Labels: Review effort [1-5]: 3

#539 feat(schema, api-client): Migrate secret types and schemas to @keyshade/schema
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/schema/src/index.types.ts
  packages/schema/src/secret.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/tests/secret.spec.ts
Labels: Review effort [1-5]: 3

#541 docs: Add pictures to Bruno setup
  blob/api_collection.png
  blob/download_bruno.png
  blob/import_collection.png
  blob/open_bruno.png
  docs/contributing-to-keyshade/running-things-locally/api-testing.md
Labels: Review effort [1-5]: 1

#544 chore(package): Fixed tests and did housekeeping
  package.json
  packages/api-client/package.json
  packages/api-client/src/controllers/user.ts
  packages/api-client/tests/user.spec.ts
  packages/api-client/tests/workspace-membership.spec.ts
  packages/schema/src/auth/index.ts
  packages/schema/src/auth/index.types.ts
  packages/schema/src/environment/index.ts
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/pagination/index.ts
  packages/schema/src/pagination/index.types.ts
  packages/schema/src/project/index.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/user/index.ts
  packages/schema/src/workspace/index.ts
  packages/schema/src/workspace/index.types.ts
  packages/schema/tests/auth.spec.ts
  packages/schema/tests/pagination.spec.ts
  packages/schema/tests/workspace.spec.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 2

#545 feat(schema, api-client): Migrate variable schemas and types to @keyshade/schema
  packages/api-client/src/controllers/variable.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/schema/.npmignore
  packages/schema/src/index.types.ts
  packages/schema/src/variable.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
  packages/schema/src/workspace/index.ts
  packages/schema/src/workspace/index.types.ts
  packages/schema/tests/variable.spec.ts
  packages/schema/tests/workspace.spec.ts
Labels: Review effort [1-5]: 3

#546 feat(schema, api-client): Migrate event schemas and types to @keyshade/schema
  packages/api-client/src/controllers/event.ts
  packages/api-client/src/types/event.types.d.ts
  packages/schema/package.json
  packages/schema/src/enums.ts
  packages/schema/src/event/index.ts
  packages/schema/src/event/index.types.ts
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/project/index.ts
  packages/schema/tests/enums.test.ts
  packages/schema/tests/event.spec.ts
  packages/schema/tests/project.spec.ts
Labels: Review effort [1-5]: 2

#547 feat(schema, api-client): Migrate integration schemas and types to @keyshade/schema
  packages/api-client/src/controllers/integration.ts
  packages/api-client/src/controllers/user.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/schema/src/index.types.ts
  packages/schema/src/integration.ts
  packages/schema/src/integration/index.ts
  packages/schema/src/integration/index.types.ts
  packages/schema/src/project/index.ts
  packages/schema/tests/integration.spec.ts
Labels: Review effort [1-5]: 2

#522 feat(platform): updated the empty state of dashboard
  apps/platform/public/svg/dashboard/folder.svg
  apps/platform/public/svg/dashboard/index.ts
  apps/platform/src/app/(main)/page.tsx
Labels: Review effort [1-5]: 2

#557 feat(schema, api-client, api, cli): Add api-key schemas and types; Fix schema inconsistencies; Minor fix for CLI build errors
  api-collection/Integration Controller/Create integration.bru
  api-collection/Integration Controller/Update integration.bru
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/project/create.project.ts
  apps/cli/src/commands/run.command.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/secret/update.secret.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/variable/update.variable.ts
  apps/cli/src/commands/workspace/search.workspace.ts
  packages/api-client/src/controllers/api-key.ts
  packages/api-client/src/controllers/environment.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/tests/api-key.spec.ts
  packages/api-client/tests/environment.spec.ts
  packages/api-client/tests/project.spec.ts
  packages/schema/src/api-key.ts
  packages/schema/src/api-key/index.ts
  packages/schema/src/api-key/index.types.ts
  packages/schema/src/environment/index.ts
  packages/schema/src/event/index.ts
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/integration/index.ts
  packages/schema/src/pagination/index.ts
  packages/schema/src/project/index.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/workspace/index.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/environment.spec.ts
  packages/schema/tests/integration.spec.ts
  packages/schema/tests/pagination.spec.ts
  packages/schema/tests/project.spec.ts
  packages/schema/tests/secret.spec.ts
  packages/schema/tests/user.spec.ts
  packages/schema/tests/variable.spec.ts
  packages/schema/tests/workspace.spec.ts
  packages/schema/tsconfig.json
Labels: Review effort [1-5]: 2

#564 chore: Update Turbo to 2.3.1
  package.json
  turbo.json
Labels: Review effort [1-5]: 2
