Repository keyshade-xyz/keyshade, pull requests merged in 2024-02, with the labels that each got.

#106 refactor: addressed sonarqube lints
  apps/api/Dockerfile
  apps/api/src/common/api-key-roles.ts
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/web/Dockerfile
Labels: enhancement, Review effort [1-5]: 2, type: refactor

#108 feat(nx-cloud): setup nx workspace
  nx.json
Labels: enhancement, Possible security concern, Review effort [1-5]: 1

#114 feat(api): updated functionality of API key
  .github/workflows/api.yaml
  .github/workflows/web.yaml
  .gitignore
  apps/api/project.json
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/dto/create.api-key/create.api-key.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/app/app.module.ts
  apps/api/src/auth/auth.types.ts
  apps/api/src/auth/guard/admin/admin.guard.spec.ts
  apps/api/src/auth/guard/admin/admin.guard.ts
  apps/api/src/auth/guard/api-key/api-key.guard.spec.ts
  apps/api/src/auth/guard/api-key/api-key.guard.ts
  apps/api/src/auth/guard/auth/auth.guard.spec.ts
  apps/api/src/auth/guard/auth/auth.guard.ts
  apps/api/src/common/add-hours-to-date.ts
  apps/api/src/decorators/forbid-api-key.decorator.ts
  apps/api/src/decorators/required-api-key-authorities.decorator.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/prisma/migrations/20240207074807_modify_api_key/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/user/controller/user.controller.ts
  apps/api/src/workspace-role/controller/workspace-role.controller.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  codecov.yml
  package.json
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#112 chore(auth): loading github module optionally
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/controller/auth.controller.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/config/config.module.ts
  apps/api/src/config/factory/github/github-strategy.factory.spec.ts
  apps/api/src/config/factory/github/github-strategy.factory.ts
  apps/api/src/config/factory/oauth-strategy.factory.ts
  apps/api/src/config/oauth-strategy/github/github.strategy.spec.ts
  apps/api/src/config/oauth-strategy/github/github.strategy.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#129 chore: migrate from supabase to postgresql
  .dockerignore
  .env.example
  .github/workflows/api.yaml
  .gitignore
  .husky/pre-commit
  apps/api/src/app/app.module.ts
  apps/api/src/supabase/supabase.module.ts
  apps/api/src/supabase/supabase.service.spec.ts
  apps/api/src/supabase/supabase.service.ts
  docker-compose-test.yml
  docker-compose.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3

#136 chore(version): Upgrade next from 14.0.4 to 14.1.0
  package.json
Labels: enhancement, Review effort [1-5]: 1

#137 chore(version): Upgrade reflect-metadata from 0.1.14 to 0.2.1
  package.json
Labels: enhancement, Review effort [1-5]: 1

#132 test: Add failing tests in util.spec.ts
  apps/api/src/common/util.spec.ts
Labels: Tests, Review effort [1-5]: 2

#139 pref: Migrated from RSA to ECC
  apps/api/src/common/create-key-pair.ts
  apps/api/src/common/decrypt.ts
  apps/api/src/common/encrypt.ts
  apps/api/src/common/util.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/service/secret.service.ts
  package.json
Labels: enhancement, Review effort [1-5]: 3

#140 test: Add event E2E tests
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/common/cleanup.ts
  apps/api/src/common/create-event.ts
  apps/api/src/event/controller/event.controller.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/prisma/migrations/20240212183333_update_event/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/tsconfig.app.json
  apps/api/tsconfig.spec.json
  package.json
Labels: enhancement, Tests, Review effort [1-5]: 4

#141 test(api): add test for workspace
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/prisma/migrations/20240215135023_update_authority/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#142 test: add project e2e tests
  apps/api/src/common/fetch-events.ts
  apps/api/src/common/get-project-with-authority.ts
  apps/api/src/common/get-workspace-with-authority.ts
  apps/api/src/common/query.transform.pipe.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/prisma/migrations/20240216062710_update_project/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#143 test: add environment e2e tests
  apps/api/src/common/get-environment-with-authority.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/prisma/migrations/20240216155823_add_unique_key_to_environment/migration.sql
  apps/api/src/prisma/schema.prisma
  codecov.yml
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#133 feat(api): Add Sentry Integeration
  .env.example
  .gitignore
  apps/api/src/main.ts
  apps/api/webpack.config.js
  docs/contributing-to-keyshade/environment-variables.md
  package.json
  tsconfig.base.json
Labels: enhancement, Review effort [1-5]: 3, configuration changes, dependencies

#144 chore(husky): Remove `e2e:api` command from husky
  .husky/pre-commit
Labels: enhancement, Review effort [1-5]: 1

#148 test(api): add e2e tests for secret
  apps/api/src/common/get-collective-project-authorities.ts
  apps/api/src/common/get-environment-with-authority.ts
  apps/api/src/common/get-project-with-authority.ts
  apps/api/src/common/get-secret-with-authority.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/prisma/migrations/20240218085410_add_unique_constraint_in_secret/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/workspace-role/controller/workspace-role.controller.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#149 feat(api): Add support for storing and managing variables
  apps/api/src/app/app.module.ts
  apps/api/src/common/cleanup.ts
  apps/api/src/common/create-event.ts
  apps/api/src/common/get-default-project-environemnt.ts
  apps/api/src/common/get-variable-with-authority.ts
  apps/api/src/event/controller/event.controller.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/prisma/migrations/20240219163241_add_variable/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/variable/controller/variable.controller.spec.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/dto/create.variable/create.variable.spec.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/dto/update.variable/update.variable.spec.ts
  apps/api/src/variable/dto/update.variable/update.variable.ts
  apps/api/src/variable/service/variable.service.spec.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/variable/variable.module.ts
  apps/api/src/variable/variable.types.ts
Labels: enhancement, Tests, Review effort [1-5]: 4

#150 test(api): Improve coverage
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/auth/auth.e2e.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/workspace-role/controller/workspace-role.controller.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#151 feat(api): Add note to secret and variable
  apps/api/src/common/get-default-project-environment.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/prisma/migrations/20240222062319_add_note_to_secret_and_variable/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
Labels: enhancement, Review effort [1-5]: 3

#152 feat(api): Add feature to export data of a workspace
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, Possible security concern, Tests, Review effort [1-5]: 2
