Repository keyshade-xyz/keyshade, pull requests merged in 2024-12, with the labels that each got.

#568 feat(schema, api-client): Migrate workspace-role schemas and types to @keyshade/schema
  package.json
  packages/api-client/src/controllers/workspace-role.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/tests/workspace-role.spec.ts
  packages/api-client/tsconfig.json
  packages/eslint-config-custom/package.json
  packages/schema/src/index.types.ts
  packages/schema/src/workspace-role.ts
  packages/schema/src/workspace-role/index.ts
  packages/schema/src/workspace-role/index.types.ts
  packages/schema/tests/enums.test.ts
  packages/schema/tests/workspace-role.spec.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 2

#476 feat(api): Add workspace removal notification email template
  apps/api/jest.config.ts
  apps/api/jest.e2e-config.ts
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/mail/emails/workspace-removal.tsx
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/socket/change-notifier.socket.ts
  apps/api/src/workspace-membership/service/workspace-membership.service.ts
  apps/api/tsconfig.json
  package.json
  packages/eslint-config-custom/package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 2

#571 fix: resolve loading SVG blocking input field interaction
  apps/platform/src/app/auth/page.tsx
  pnpm-lock.yaml
Labels: Review effort [1-5]: 1

#569 feat(schema, api-client): Migrate workspace-membership schemas and types to @keyshade/schema
  api-collection/Workspace Membership Controller/Remove users from workspace.bru
  apps/api/src/workspace-membership/controller/workspace-membership.controller.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  packages/api-client/src/controllers/workspace-membership.ts
  packages/api-client/src/core/client.ts
  packages/api-client/src/types/workspace-membership.types.d.ts
  packages/api-client/tests/config/setup.ts
  packages/api-client/tests/workspace-membership.spec.ts
  packages/eslint-config-custom/package.json
  packages/schema/src/index.ts
  packages/schema/src/index.types.ts
  packages/schema/src/user/index.ts
  packages/schema/src/workspace-membership/index.ts
  packages/schema/src/workspace-membership/index.types.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/user.spec.ts
  packages/schema/tests/workspace-membership.spec.ts
  turbo.json
Labels: Review effort [1-5]: 3

#574 feat(schema): Add User type inference from UserSchema
  packages/schema/src/user/index.types.ts
Labels: Review effort [1-5]: 1

#540 feat(platform): Added screen for CREATE NEW PROJECT
  apps/api/package-lock.json
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/project.types.ts
  apps/api/src/project/service/project.service.ts
  apps/platform/.eslintrc.cjs
  apps/platform/package.json
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/settings/@profile/page.tsx
  apps/platform/src/app/auth/otp/page.tsx
  apps/platform/src/app/auth/page.tsx
  apps/platform/src/components/dashboard/projectCard/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/ui/select.tsx
  apps/platform/src/lib/api-functions/projects.ts
  apps/platform/src/lib/api-functions/secrets.ts
  apps/platform/src/lib/workspace-storage.ts
  apps/platform/src/types/index.ts
  apps/platform/tsconfig.json
  packages/api-client/src/controllers/project.ts
  packages/eslint-config-custom/package-lock.json
  packages/schema/src/project/index.ts
  packages/schema/src/project/index.types.ts
  packages/schema/tests/project.spec.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 3

#577 refactor(schema): add describe blocks in tests for each kind of schema
  packages/schema/src/secret/index.ts
  packages/schema/src/variable/index.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/auth.spec.ts
  packages/schema/tests/enums.test.ts
  packages/schema/tests/environment.spec.ts
  packages/schema/tests/event.spec.ts
  packages/schema/tests/integration.spec.ts
  packages/schema/tests/pagination.spec.ts
  packages/schema/tests/secret.spec.ts
  packages/schema/tests/user.spec.ts
  packages/schema/tests/variable.spec.ts
  packages/schema/tests/workspace-membership.spec.ts
  packages/schema/tests/workspace-role.spec.ts
  packages/schema/tests/workspace.spec.ts
Labels: Review effort [1-5]: 2

#580 fix(api): Enable global project access
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
Labels: Review effort [1-5]: 2

#480 feat: Add email template for inviting user to workspace
  apps/api/src/mail/emails/components/base-email-template.tsx
  apps/api/src/mail/emails/styles/common-styles.ts
  apps/api/src/mail/emails/workspace-invitation.tsx
  apps/api/src/mail/emails/workspace-removal.tsx
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/workspace-membership/service/workspace-membership.service.ts
Labels: enhancement, Review effort [1-5]: 2, hacktoberfest-accepted

#581 feat(api): add logout endpoint to clear token cookie
  api-collection/Auth Controller/Logout.bru
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
Labels: Review effort [1-5]: 1

#582 feat: Add email template for sending OTP to the user
  apps/api/src/mail/emails/otp-email-template.tsx
  apps/api/src/mail/emails/styles/common-styles.ts
  apps/api/src/mail/services/mail.service.ts
Labels: Review effort [1-5]: 2

#586 feat(api): Add endpoint to fetch all workspace invitations for a user
  api-collection/Workspace Controller/Get all invitations of user.bru
  apps/api/src/environment/dto/create.environment/create.environment.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/prisma/migrations/20241211205448_add_created_on_in_workspace_member/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/workspace-membership/service/workspace-membership.service.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: Review effort [1-5]: 2

#579 refactor: Changed the text in the hero section of the web application
  apps/web/src/components/hero/index.tsx
Labels: Review effort [1-5]: 1

#585 feat(platofrm): Added online/offline status detection in the platform
  apps/platform/src/app/layout.tsx
  apps/platform/src/components/common/online-status-handler.tsx
  apps/platform/src/hooks/use-online-status.ts
Labels: Review effort [1-5]: 2

#589 feat(cli): Add functionality to operate on Workspace Membership
  apps/api/src/mail/emails/components/base-email-template.tsx
  apps/api/src/mail/emails/workspace-invitation.tsx
  apps/api/src/mail/emails/workspace-removal.tsx
  apps/cli/src/commands/workspace.command.ts
  apps/cli/src/commands/workspace/membership.workspace.ts
  apps/cli/src/commands/workspace/membership/accept-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/cancel-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/decline-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/get-all-members.membership.ts
  apps/cli/src/commands/workspace/membership/invite.membership.ts
  apps/cli/src/commands/workspace/membership/leave.membership.ts
  apps/cli/src/commands/workspace/membership/remove.membership.ts
  apps/cli/src/commands/workspace/membership/transfer-ownership.membership copy.ts
  apps/cli/src/commands/workspace/membership/update-role.membership.ts
  apps/cli/src/commands/workspace/role/update.role.ts
  apps/cli/src/util/controller-instance.ts
  package.json
Labels: Review effort [1-5]: 3

#584 chore(platoform): Swapped all legacy API calls with `@keyshade/api-client`
  apps/platform/.eslintrc.cjs
  apps/platform/Dockerfile
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/project/[project]/layout.tsx
  apps/platform/src/app/(main)/settings/@profile/page.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/lib/api-client.ts
  apps/platform/src/lib/controller-instance.ts
  apps/platform/src/lib/workspace-storage.ts
  erDetails(userData)
  packages/api-client/src/index.ts
  packages/schema/src/secret/index.ts
  packages/schema/tests/secret.spec.ts
  t updateSelf = useCallback(async () => {
  t.success('User details updated successfully')
Labels: Review effort [1-5]: 3

#592 feat(workflows): Add internal package dependencies to existing workflows
  .github/workflows/validate-api-client.yaml
  .github/workflows/validate-api.yaml
  .github/workflows/validate-cli.yaml
  .github/workflows/validate-platform.yaml
  .github/workflows/validate-schema.yaml
  .github/workflows/validate-secret-scan.yaml
  .github/workflows/validate-web.yaml
  package.json
Labels: Review effort [1-5]: 2
