Repository keyshade-xyz/keyshade, pull requests merged in 2024-01, with the labels that each got.

#71 patch: send email async
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/mail/services/mail.service.ts
Labels: bug_fix

#72 feat: added the auto assign workflow yaml file
  .github/workflows/auto-assign.yaml
  CONTRIBUTIONS.md
Labels: enhancement

#74 fix: issue auto assign cannot read properties of undefined assignees
  .github/workflows/auto-assign.yaml
Labels: bug_fix

#73 chore: create a cron job function that will run every hour to clean up expired otps
  apps/api/src/auth/repository/auth.repository.ts
  apps/api/src/auth/repository/interface.repository.ts
  apps/api/src/auth/repository/mock.repository.ts
  apps/api/src/auth/service/auth.service.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#50 chore(eslint): Fix Lint Rules
  .eslintrc.json
  apps/api-e2e/project.json
  apps/api/project.json
  apps/cli/package.json
  apps/cli/project.json
  apps/web/project.json
  packages/sdk-node/project.json
Labels: enhancement

#79 feat: dockerize api
  .github/workflows/web.yaml
  apps/api/.dockerignore
  apps/api/Dockerfile
  apps/web/.dockerignore
  apps/web/Dockerfile
  package.json
Labels: enhancement

#77 feat: create user endpoint
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/user/controller/user.controller.spec.ts
  apps/api/src/user/controller/user.controller.ts
  apps/api/src/user/dto/create.user/create.user.ts
  apps/api/src/user/service/user.service.spec.ts
  apps/api/src/user/service/user.service.ts
Labels: enhancement

#88 test: adding test command to pre commit
  .husky/pre-commit
Labels: enhancement

#90 docs: update README.md
  README.md
Labels: documentation, Review effort [1-5]: 1

#93 Update README.md
  README.md
Labels: documentation

#100 chore: Remove SDK folders
  Cargo.lock
  Cargo.toml
  package.json
  packages/.gitkeep
  packages/sdk-node/.eslintrc.json
  packages/sdk-node/README.md
  packages/sdk-node/jest.config.ts
  packages/sdk-node/package.json
  packages/sdk-node/project.json
  packages/sdk-node/src/index.ts
  packages/sdk-node/src/lib/sdk-js.spec.ts
  packages/sdk-node/src/lib/sdk-js.ts
  packages/sdk-node/tsconfig.json
  packages/sdk-node/tsconfig.lib.json
  packages/sdk-node/tsconfig.spec.json
  packages/sdk-rust/Cargo.toml
  packages/sdk-rust/project.json
  packages/sdk-rust/src/lib.rs
Labels: enhancement, Review effort [1-5]: 2

#101 feat: AutoCreate Admin On Startup
  .env.example
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/user/service/user.service.ts
  apps/web/tsconfig.json
Labels: enhancement, type: feature, Review effort [1-5]: 3
