Repository keyshade-xyz/keyshade, pull requests merged in 2024-05, with the labels that each got.

#202 chore: Update deprecated husky Install command
  package.json
Labels: enhancement, Review effort [1-5]: 1

#200 chore(api): Added type inference and runtime validation to `process.env`
  .env.example
  .github/workflows/release.yml
  .github/workflows/validate-api.yaml
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/auth/guard/auth/auth.guard.ts
  apps/api/src/common/env/env.d.ts
  apps/api/src/common/env/env.schema.ts
  apps/api/src/user/service/user.service.ts
  package.json
  pnpm-lock.yaml
Labels: documentation, enhancement, Review effort [1-5]: 3

#212 feat(api): Add OAuth redirection and polished authentication
  .env.example
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/common/create-user.ts
  apps/api/src/common/env/env.schema.ts
  apps/api/src/common/redirect.ts
  apps/api/src/common/set-cookie.ts
  apps/api/src/prisma/migrations/20240512141423_add_auth_provider/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/user/service/user.service.ts
  apps/api/src/user/user.e2e.spec.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#215 test(api): Refactor project e2e tests to be more readable
  apps/api/src/app/app.module.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/user/service/user.service.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#220 chore: Remove swagger docs
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/dto/create.api-key/create.api-key.ts
  apps/api/src/app/app.controller.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/event/controller/event.controller.ts
  apps/api/src/feedback/controller/feedback.controller.ts
  apps/api/src/integration/controller/integration.controller.ts
  apps/api/src/main.ts
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/variable/controller/variable.controller.ts
Labels: enhancement, documentation, Review effort [1-5]: 2

#224 test(api): Refactored e2e tests
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/service/api-key.service.ts
  pnpm-lock.yaml
Labels: enhancement, tests, Review effort [1-5]: 2

#225 feat(platfrom): add delete method in api client
  apps/platform/src/lib/api-client.ts
Labels: enhancement

#226 feat(web): Add and link privacy and tnc page
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/src/app/(main)/(mdx)/layout.tsx
  apps/web/src/app/(main)/(mdx)/privacy/page.mdx
  apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
  apps/web/src/components/shared/card/index.tsx
  apps/web/src/components/shared/footer/index.tsx
  apps/web/src/mdx-components.tsx
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3

#228 fix(web): Docker next config not found
  apps/web/Dockerfile
Labels: bug_fix, Review effort [1-5]: 1

#234 docs: Fix typo in organization-of-code.md
  docs/contributing-to-keyshade/design-of-our-code/organization-of-code.md
Labels: documentation, Review effort [1-5]: 1

#230 refactor(api): Replaced OTP code from alphanumeric to numeric
  apps/api/src/auth/service/auth.service.ts
Labels: enhancement, Review effort [1-5]: 2

#236 chore(api): Get feedback forward email from process.env
  .env.example
  apps/api/src/common/env/env.schema.ts
  apps/api/src/feedback/service/feedback.service.ts
  docs/contributing-to-keyshade/environment-variables.md
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#237 feat(api): add `minio-client` provider
  .env.example
  apps/api/package.json
  apps/api/src/common/env/env.schema.ts
  apps/api/src/feedback/service/feedback.service.ts
  apps/api/src/provider/minio.provider.ts
  apps/api/src/provider/provider.module.ts
  docker-compose-test.yml
  docker-compose.yml
  docs/contributing-to-keyshade/environment-variables.md
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, documentation, configuration changes

#242 test: Refactored workspace e2e tests
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, tests, Review effort [1-5]: 4

#248 test: Refactor workspace role e2e tests
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, tests, Review effort [1-5]: 2
