Repository keyshade-xyz/keyshade, pull requests merged in 2024-06, with the labels that each got.

#266 refactor(api): Replace for loop with array indexing while decrypting secrets during bulk fetch #265
  apps/api/src/secret/service/secret.service.ts
Labels: enhancement, Review effort [1-5]: 2

#270 refactor(api)!: Refactor environment, secret and variable functionality
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/approval/approval.e2e.spec.ts
  apps/api/src/approval/approval.module.ts
  apps/api/src/approval/approval.types.ts
  apps/api/src/approval/controller/approval.controller.spec.ts
  apps/api/src/approval/controller/approval.controller.ts
  apps/api/src/approval/service/approval.service.spec.ts
  apps/api/src/approval/service/approval.service.ts
  apps/api/src/common/alphanumeric-reason-pipe.spec.ts
  apps/api/src/common/alphanumeric-reason-pipe.ts
  apps/api/src/common/authority-checker.service.ts
  apps/api/src/common/create-approval.ts
  apps/api/src/common/create-event.ts
  apps/api/src/common/create-workspace.ts
  apps/api/src/common/get-default-project-environment.ts
  apps/api/src/common/workspace-approval-enabled.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/environment/dto/create.environment/create.environment.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/integration/integration.types.ts
  apps/api/src/integration/plugins/discord/discord.integration.spec.ts
  apps/api/src/integration/plugins/discord/discord.integration.ts
  apps/api/src/integration/service/integration.service.ts
  apps/api/src/prisma/migrations/20240611165845_refactor_environment_and_versions/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/secret.types.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/variable/variable.types.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/dto/create.workspace/create.workspace.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  apps/platform/src/types/index.ts
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 5, Tests

#269 docs: added running-the-web-app.md
  docs/contributing-to-keyshade/running-things-locally/running-the-web-app.md
Labels: Review effort [1-5]: 1, Documentation

#267 fix(web): resolve encryption glitch in footer text
  apps/web/src/components/ui/encrypt-text.tsx
Labels: Review effort [1-5]: 2, Bug fix

#286 feat(api): Add `requireRestart` parameter
  apps/api/src/prisma/migrations/20240625190757_add_require_restart_field/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/socket/socket.types.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/platform/src/lib/workspace-storage.ts
Labels: enhancement, Review effort [1-5]: 3, Documentation

#289 feat(cli): Added CLI
  .gitignore
  apps/api/package.json
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/auth/guard/auth/auth.guard.ts
  apps/api/src/prisma/migrations/20240625190757_add_require_restart_field/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/socket/change-notifier.socket.ts
  apps/api/src/socket/socket.types.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/cli/.eslintrc.js
  apps/cli/package.json
  apps/cli/src/commands/base/command.interface.ts
  apps/cli/src/commands/configure/configure.command.ts
  apps/cli/src/commands/configure/configure.types.d.ts
  apps/cli/src/commands/run/run.command.ts
  apps/cli/src/commands/run/run.types.d.ts
  apps/cli/src/http/auth.ts
  apps/cli/src/http/index.ts
  apps/cli/src/http/secret.ts
  apps/cli/src/http/variable.ts
  apps/cli/src/index.ts
  apps/cli/src/util/configuration.ts
  apps/cli/src/util/constants.ts
  apps/cli/src/util/logger.ts
  apps/cli/tsconfig.json
  docker-compose.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Documentation

#282 chore(web): Update Terms and Conditions and Privacy Policy
  apps/web/src/app/(main)/(mdx)/privacy/page.mdx
  apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
Labels: Review effort [1-5]: 4, Bug fix, Documentation

#268 docs(web): Add documentation about our web package
  docs/SUMMARY.md
  docs/contributing-to-keyshade/design-of-our-code/README.md
  docs/contributing-to-keyshade/design-of-our-code/web.md
Labels: Review effort [1-5]: 1, Documentation
