Repository keyshade-xyz/keyshade, pull requests merged in 2024-07, with the labels that each got.

#310 refactor(cli): Updated configuration commands and mechanism
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/base/command.interface.ts
  apps/cli/src/commands/configure/configure.command.ts
  apps/cli/src/commands/configure/configure.types.d.ts
  apps/cli/src/commands/init.command.ts
  apps/cli/src/commands/profile.command.ts
  apps/cli/src/commands/profile/create.profile.ts
  apps/cli/src/commands/profile/delete.profile.ts
  apps/cli/src/commands/profile/list.profile.ts
  apps/cli/src/commands/profile/update.profile.ts
  apps/cli/src/commands/profile/use.profile.ts
  apps/cli/src/commands/run.command.ts
  apps/cli/src/http/secret.ts
  apps/cli/src/http/variable.ts
  apps/cli/src/index.ts
  apps/cli/src/types/command/command.types.d.ts
  apps/cli/src/types/command/profile.types.d.ts
  apps/cli/src/types/command/run.types.d.ts
  apps/cli/src/types/index.types.d.ts
  apps/cli/src/util/configuration.ts
Labels: enhancement, Review effort [1-5]: 4, Other

#313 feat(platform): View secrets
  apps/platform/package.json
  apps/platform/public/svg/secret/index.ts
  apps/platform/public/svg/secret/noteIcon.svg
  apps/platform/public/svg/secret/secretLogo.svg
  apps/platform/src/app/(main)/layout.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/project/[project]/layout.tsx
  apps/platform/src/components/dashboard/projectCard/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/ui/accordion.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/ui/tooltip.tsx
  apps/platform/src/lib/api-functions/projects.ts
  apps/platform/src/lib/api-functions/secrets.ts
  apps/platform/src/types/index.ts
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Bug fix, Documentation

#329 docs(cli): Added docs for the CLI package
  apps/cli/src/commands/init.command.ts
  docs/SUMMARY.md
  docs/contributing-to-keyshade/design-of-our-code/README.md
  docs/contributing-to-keyshade/design-of-our-code/cli.md
  docs/contributing-to-keyshade/design-of-our-code/web.md
  docs/contributing-to-keyshade/running-things-locally/README.md
  docs/contributing-to-keyshade/running-things-locally/running-the-api.md
  docs/contributing-to-keyshade/running-things-locally/running-the-cli.md
Labels: enhancement, Review effort [1-5]: 2, Documentation

#330 docs(cli): Added usage docs
  docs/SUMMARY.md
  docs/cli/init.md
  docs/cli/introduction.md
  docs/cli/profile.md
  docs/cli/run.md
  docs/contributing-to-keyshade/design-of-our-code/organization-of-code.md
  docs/contributing-to-keyshade/environment-variables.md
  docs/internals/architecture-of-keyshade.md
  docs/internals/how-the-cli-works.md
Labels: Review effort [1-5]: 1, Documentation

#331 refactor(cli): Refactored profile commands into readable blocks
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/profile/create.profile.ts
  apps/cli/src/commands/profile/delete.profile.ts
  apps/cli/src/commands/profile/list.profile.ts
  apps/cli/src/commands/profile/update.profile.ts
  apps/cli/src/commands/profile/use.profile.ts
  apps/cli/src/util/profile.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#358 docs: Added docker details in setting-things-up.md
  docs/contributing-to-keyshade/running-things-locally/running-the-api.md
  docs/contributing-to-keyshade/setting-things-up.md
Labels: Review effort [1-5]: 1, Documentation

#335 feat(platform): Add warning sonner toast for invalid otp
  apps/platform/src/app/auth/otp/page.tsx
  apps/platform/src/components/ui/input-otp.tsx
  package.json
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#334 feat(cli): Improved the DX for list profile
  apps/cli/.eslintrc.js
  apps/cli/.swcrc
  apps/cli/package.json
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/init.command.ts
  apps/cli/src/commands/profile.command.ts
  apps/cli/src/commands/profile/create.profile.ts
  apps/cli/src/commands/profile/delete.profile.ts
  apps/cli/src/commands/profile/list.profile.ts
  apps/cli/src/commands/profile/update.profile.ts
  apps/cli/src/commands/profile/use.profile.ts
  apps/cli/src/commands/run.command.ts
  apps/cli/src/http/auth.ts
  apps/cli/src/http/secret.ts
  apps/cli/src/http/variable.ts
  apps/cli/src/index.ts
  apps/cli/src/types/index.types.d.ts
  apps/cli/src/util/configuration.ts
  apps/cli/src/util/logger.ts
  apps/cli/src/util/profile.ts
  apps/cli/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, Dependencies

#374 fix(platform): Platform types fixes
  apps/api/package.json
  apps/cli/package.json
  apps/platform/package.json
  apps/web/package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 1, Dependencies

#402 feat(api): Improve handling of edge cases for paginate module
  apps/api/src/common/paginate.spec.ts
  apps/api/src/common/paginate.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#375 feat(chore): Update auto-assign.yaml
  .github/workflows/auto-assign.yaml
Labels: foss hack

#376 chore(API): Skip workspace creation when user is admin
  apps/api/src/common/create-user.ts
  apps/api/src/user/user.e2e.spec.ts
Labels: foss hack

#306 chore(cli): Changed objects to classes
  apps/cli/src/http/auth.ts
  apps/cli/src/http/secret.ts
  apps/cli/src/http/variable.ts
Labels: enhancement, Review effort [1-5]: 2, foss hack

#303 feat(api): Create endpoint for fetching all revisions of a secret
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
Labels: enhancement, Review effort [1-5]: 3, foss hack, Tests

#304 feat(api): Create endpoint for fetching all revisions of a variable
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
Labels: enhancement, Review effort [1-5]: 3, foss hack, Tests

#324 feat(cli): Add functionality to operate on Environments
  apps/cli/package.json
  apps/cli/src/commands/environment.command.ts
  apps/cli/src/commands/environment/create.environment.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/environment/get.environment.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/environment/update.environment.ts
  apps/cli/src/commands/run.command.ts
  apps/cli/src/http/auth.ts
  apps/cli/src/http/project.ts
  apps/cli/src/http/secret.ts
  apps/cli/src/http/variable.ts
  apps/cli/src/index.ts
  apps/cli/src/types/command/run.types.d.ts
  apps/cli/src/util/decrypt.ts
  apps/cli/src/util/fileUtils.ts
  apps/cli/tsconfig.json
  package.json
  packages/api-client/package-lock.json
  packages/api-client/package.json
  packages/api-client/src/controllers/environment/environment.ts
  packages/api-client/src/core/client.ts
  packages/api-client/src/core/response-parser.ts
  packages/api-client/src/index.ts
  packages/api-client/src/types/index.types.d.ts
  packages/api-client/tests/environment.spec.ts
  packages/api-client/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, Dependencies
