Repository keyshade-xyz/keyshade, pull requests merged in 2024-08, with the labels that each got.

#377 feat(api): Add max page size
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/common/limit-max-items-per-page.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/integration/service/integration.service.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/user/service/user.service.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace/service/workspace.service.ts
Labels: foss hack

#399 feat(api-client): Create controller for Event module
  packages/api-client/src/controllers/event/event.ts
  packages/api-client/src/types/event.types.d.ts
  packages/api-client/tests/event.spec.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#397 feat(api-client): Create controller for Integration module
  packages/api-client/src/controllers/integration.ts
  packages/api-client/src/index.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/api-client/tests/integration.spec.ts
Labels: enhancement, Review effort [1-5]: 2

#408 fix(api): Add NotFound exception on passing an invalid roleId while inviting user in workspace
  apps/api/src/workspace/service/workspace.service.ts
Labels: Review effort [1-5]: 2

#385 fix(platform): Build failure in platform
  apps/platform/src/app/api/health/route.ts
  apps/platform/src/components/ui/command.tsx
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#370 feat(api-client): Create controller for Project module
  packages/api-client/jest.config.ts
  packages/api-client/src/controllers/environment.ts
  packages/api-client/src/controllers/event.ts
  packages/api-client/src/controllers/integration.ts
  packages/api-client/src/controllers/project.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/variable.ts
  packages/api-client/src/core/response-parser.ts
  packages/api-client/src/types/environment.types.d.ts
  packages/api-client/src/types/event.types.d.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/api-client/src/types/project.types.d.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/api-client/tests/environment.spec.ts
  packages/api-client/tests/project.spec.ts
  packages/api-client/tsconfig.json
  packages/tsconfig/base.json
Labels: foss hack
