Repository keyshade-xyz/keyshade, pull requests merged in 2024-10, with the labels that each got.

#470 feat: Add more logging to Sentry init
  apps/api/src/common/env/env.schema.ts
  apps/api/src/main.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#469 feat(cli): implement commands to get, list, update, and delete, workspace roles
  apps/cli/src/commands/workspace.command.ts
  apps/cli/src/commands/workspace/role.workspace.ts
  apps/cli/src/commands/workspace/role/delete.role.ts
  apps/cli/src/commands/workspace/role/get.role.ts
  apps/cli/src/commands/workspace/role/list.role.ts
  apps/cli/src/commands/workspace/role/update.role.ts
Labels: enhancement, Review effort [1-5]: 3, Documentation

#473 docs: Added documentation for running the platform
  docs/SUMMARY.md
  docs/contributing-to-keyshade/running-things-locally/running-the-platform.md
Labels: Review effort [1-5]: 1, Documentation, hacktoberfest-accepted

#477 chore: Update controller invocation in environment commands
  apps/cli/src/commands/environment/create.environment.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/environment/get.environment.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/environment/update.environment.ts
Labels: enhancement, Review effort [1-5]: 2, hacktoberfest-accepted

#481 chore: Clearing email field after waitlisting the user email
  apps/web/src/components/hero/index.tsx
Labels: enhancement, Review effort [1-5]: 2, hacktoberfest-accepted

#484 feat(api): API-CLIENT: Create controller for User module
  packages/api-client/src/controllers/user.ts
  packages/api-client/src/types/user.types.d.ts
  packages/api-client/tests/user.spec.ts
Labels: enhancement, Review effort [1-5]: 3, Tests, hacktoberfest-accepted

#445 feat(api): Add resend otp implementation
  .env.example
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/controller/auth.controller.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/common/env/env.schema.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/commands/workspace/role/get.role.ts
  apps/cli/src/commands/workspace/role/list.role.ts
  apps/cli/src/commands/workspace/role/update.role.ts
  apps/cli/src/util/pagination-options.ts
  apps/platform/src/app/auth/page.tsx
  apps/web/src/app/(main)/career/page.tsx
  packages/api-client/src/controllers/workspace-membership.ts
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3, Dependencies

#487 chore: Email validation
  apps/web/package.json
  apps/web/src/components/hero/index.tsx
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 2, Dependencies, hacktoberfest-accepted

#468 fix(api,api-client): Add environmentSlug in multiple places across the variable module
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/api-client/tests/variable.spec.ts
Labels: Review effort [1-5]: 3, hacktoberfest-accepted

#501 docs: Add instructions for resetting the local Prisma database (#495)
  docs/contributing-to-keyshade/running-things-locally/running-the-api.md
Labels: Review effort [1-5]: 1, Documentation

#492 feat: Configured extra check for waitlisted users already in the list and created toast message for them
  apps/web/src/components/hero/index.tsx
  apps/web/tailwind.config.js
Labels: enhancement, Review effort [1-5]: 2, bug_fix, hacktoberfest-accepted

#507 chore(secret-scan): Failing lint issues
  packages/secret-scan/src/rules/authress.ts
  packages/secret-scan/src/rules/beamer.ts
  packages/secret-scan/src/rules/bitbucket.ts
  packages/secret-scan/src/rules/cloudflare.ts
  packages/secret-scan/src/rules/coinbase.ts
  packages/secret-scan/src/rules/contentful.ts
  packages/secret-scan/src/rules/definednetworking.ts
  packages/secret-scan/src/rules/dropbox.ts
  packages/secret-scan/src/rules/huggingface.ts
  packages/secret-scan/src/rules/ip_public.ts
  packages/secret-scan/src/rules/planetscale.ts
  packages/secret-scan/src/rules/sidekiq.ts
Labels: Review effort [1-5]: 2, Bug fix

#504 feat(cli): Add functionality to operate on Secrets
  apps/cli/.eslintrc.cjs
  apps/cli/src/commands/secret.command.ts
  apps/cli/src/commands/secret/create.secret.ts
  apps/cli/src/commands/secret/delete.secret.ts
  apps/cli/src/commands/secret/get.secret.ts
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/secret/update.secret.ts
  apps/cli/src/index.ts
Labels: enhancement, Review effort [1-5]: 4

#511 chore: Update pnpx commands to pnpm dlx
  .github/workflows/release.yml
  apps/api/package.json
Labels: enhancement, Review effort [1-5]: 1

#509 fix(api,api-client): Add environmentSlug in multiple places across the secret module
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/api-client/tests/secret.spec.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#514 feat(cli): Add functionality to operate on Variables
  apps/cli/src/commands/variable.command.ts
  apps/cli/src/commands/variable/create.variable.ts
  apps/cli/src/commands/variable/delete.variable.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/variable/revisions.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/variable/update.variable.ts
  apps/cli/src/index.ts
Labels: Review effort [1-5]: 4

#515 fix(cli): Removed unnecessary console log in secrets
  apps/cli/src/commands/secret/list.secret.ts
Labels: Review effort [1-5]: 1
