Repository keyshade-xyz/keyshade, pull requests merged in 2024-09, with the labels that each got.

#362 chore(cli): Add Zod validation to parseInput function
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/src/common/logger.service.ts
  apps/api/src/main.ts
  apps/api/tsconfig.app.json
  apps/api/tsconfig.json
  apps/api/tsconfig.spec.json
  apps/cli/package.json
  apps/cli/src/commands/profile/create.profile.ts
  package.json
  packages/api-client/package.json
  packages/api-client/tests/config/setup.ts
  packages/api-client/tsconfig.spec.json
  pnpm-lock.yaml
  turbo.json
Labels: enhancement, Review effort [1-5]: 2, foss hack, Tests

#411 docs: Fixed minor typo in postman workspace link
  docs/contributing-to-keyshade/running-things-locally/api-testing.md
Labels: Review effort [1-5]: 1, Documentation

#413 chore(platform): Added optional chaining due to strict null check
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/project/[project]/layout.tsx
  apps/platform/src/app/auth/invite/page.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/teams/teamTable/index.tsx
  apps/platform/src/components/ui/line-tab.tsx
  apps/platform/src/env.ts
  apps/platform/src/lib/workspace-storage.ts
  apps/platform/src/middleware.ts
  package.json
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#414 feat(API): Included default workspace details in getSelf function
  .gitignore
  apps/api/src/user/service/user.service.ts
  apps/api/src/user/user.e2e.spec.ts
  packages/eslint-config-custom/package-lock.json
  packages/tsconfig/package-lock.json
Labels: enhancement, Review effort [1-5]: 2, Tests

#418 fix: Error messages fixed in api-key service
  apps/api/src/api-key/service/api-key.service.ts
Labels: Review effort [1-5]: 2, Bug fix

#423 feat(platform): Add loading skeleton in the secrets page
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/components/ui/skeleton.tsx
Labels: enhancement, Review effort [1-5]: 2

#427 feat(api-client): Added workspace controller
  apps/api/src/app/app.module.ts
  apps/api/src/auth/auth.types.ts
  apps/api/src/auth/guard/auth/auth.guard.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/cache/cache.service.ts
  apps/api/src/common/user.ts
  apps/api/src/common/util.ts
  apps/api/src/decorators/user.decorator.ts
  apps/api/src/user/controller/user.controller.ts
  apps/api/src/user/service/user.service.ts
  apps/api/src/user/user.e2e.spec.ts
  apps/api/src/user/user.types.ts
  apps/api/src/workspace-membership/service/workspace-membership.service.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace/dto/create.workspace/create.workspace.ts
  apps/api/src/workspace/service/workspace.service.ts
  packages/api-client/src/controllers/workspace.ts
  packages/api-client/src/index.ts
  packages/api-client/src/types/workspace.types.d.ts
  packages/api-client/tests/config/setup.ts
  packages/api-client/tests/workspace.spec.ts
Labels: Review effort [1-5]: 4

#430 feat(api-client): Added workspace role controller
  packages/api-client/src/controllers/environment.ts
  packages/api-client/src/controllers/integration.ts
  packages/api-client/src/controllers/project.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/variable.ts
  packages/api-client/src/controllers/workspace-role.ts
  packages/api-client/src/controllers/workspace.ts
  packages/api-client/src/core/pagination-parser.ts
  packages/api-client/src/types/environment.types.d.ts
  packages/api-client/src/types/event.types.d.ts
  packages/api-client/src/types/index.types.d.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/api-client/src/types/project.types.d.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/src/types/workspace.types.d.ts
  packages/api-client/tests/workspace-role.spec.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#420 feat(api): Update slug generation method
  apps/api/src/common/slug-generator.spec.ts
  apps/api/src/common/slug-generator.ts
  apps/api/src/project/project.e2e.spec.ts
Labels: Review effort [1-5]: 2, Bug fix

#434 feat(api): Fetch total count of environments, secrets and variables in project
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#435 feat(API): Added icon and removed description field from workspace
  apps/api/src/common/workspace.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/prisma/migrations/20240915122629_add_icon_remove_description_from_workspace/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace/dto/create.workspace/create.workspace.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  packages/api-client/src/types/workspace.types.d.ts
  packages/api-client/tests/workspace.spec.ts
  packages/schema/src/workspace.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#436 feat(api): Add prod env schema in env file
  apps/api/src/common/env/env.schema.ts
Labels: enhancement, Review effort [1-5]: 2

#432 feat(api): Replace `projectId` with `name` and `slug` in workspace-role response.
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace-role/workspace-role.types.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/tests/workspace-role.spec.ts
Labels: Review effort [1-5]: 2, Bug fix, Tests

#441 feat(cli): Add workspace operations
  .husky/pre-commit
  apps/cli/.eslintrc.cjs
  apps/cli/package.json
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/scan.command.ts
  apps/cli/src/commands/workspace.command.ts
  apps/cli/src/commands/workspace/create.workspace.ts
  apps/cli/src/commands/workspace/delete.workspace.ts
  apps/cli/src/commands/workspace/export.workspace.ts
  apps/cli/src/commands/workspace/get.workspace.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/commands/workspace/search.workspace.ts
  apps/cli/src/commands/workspace/update.workspace.ts
  apps/cli/src/index.ts
  apps/cli/src/types/command/command.types.d.ts
  apps/cli/src/util/configuration.ts
  apps/cli/src/util/controller-instance.ts
  apps/cli/src/util/decrypt.ts
  apps/cli/tsconfig.json
  package.json
  packages/api-client/.eslintrc.cjs
  packages/api-client/package.json
  packages/api-client/src/index.ts
  packages/api-client/src/types/environment.types.d.ts
  packages/api-client/src/types/integration.types.d.ts
  packages/api-client/src/types/project.types.d.ts
  packages/api-client/src/types/secret.types.d.ts
  packages/api-client/src/types/variable.types.d.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/src/types/workspace.types.d.ts
  packages/api-client/tsconfig.json
  packages/secret-scan/package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 4, Documentation

#440 fix(web): Horizontal Scrolling issue on the website
  apps/web/src/components/colabEasy/index.tsx
  apps/web/src/components/lifeEasySection/index.tsx
  apps/web/src/components/secretSection/index.tsx
Labels: enhancement, Review effort [1-5]: 2

#444 fix: resolve footer website name cut-off or overlap issue
  apps/web/src/components/shared/footer/index.tsx
Labels: Review effort [1-5]: 1, bug_fix

#448 feat: Remove project IDs from workspace role export data and update tests
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#450 fix(platform): Fixed duplicate Google Logo UI fix
  apps/platform/public/svg/auth/gitlabSVG.svg
  apps/platform/public/svg/auth/index.ts
  apps/platform/src/app/auth/page.tsx
Labels: enhancement, Review effort [1-5]: 2, Other

#452 feat(API-CLIENT): Added workspace-membership and it's tests
  packages/api-client/src/controllers/workspace-membership.ts
  packages/api-client/src/index.ts
  packages/api-client/src/types/workspace-membership.types.d.ts
  packages/api-client/tests/workspace-membership.spec.ts
Labels: enhancement, Review effort [1-5]: 3, Tests

#451 feat(cli): Add project command
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/project/dto/fork.project/fork.project.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/cli/package.json
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/project.command.ts
  apps/cli/src/commands/project/create.project.ts
  apps/cli/src/commands/project/delete.project.ts
  apps/cli/src/commands/project/fork.project.ts
  apps/cli/src/commands/project/get.project.ts
  apps/cli/src/commands/project/list-forks.project.ts
  apps/cli/src/commands/project/list.project.ts
  apps/cli/src/commands/project/sync.project.ts
  apps/cli/src/commands/project/unlink.project.ts
  apps/cli/src/commands/project/update.project.ts
  apps/cli/src/commands/scan.command.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/index.ts
  apps/cli/src/types/command/command.types.d.ts
  packages/api-client/src/controllers/project.ts
  packages/api-client/src/types/project.types.d.ts
  packages/api-client/src/types/workspace-role.types.d.ts
  packages/api-client/tests/project.spec.ts
  packages/api-client/tests/workspace-role.spec.ts
Labels: enhancement, Review effort [1-5]: 4

#460 docs: Updated CLI docs
  docs/contributing-to-keyshade/design-of-our-code/cli.md
  docs/contributing-to-keyshade/running-things-locally/running-the-cli.md
Labels: Review effort [1-5]: 1

#455 fix(api): Replace the id with slug in the global-search service
  apps/api/src/workspace/service/workspace.service.ts
  packages/api-client/src/types/workspace.types.d.ts
Labels: Review effort [1-5]: 2, Bug fix

#461 docs: Add documentation for scan in CLI
  docs/cli/scan.md
Labels: Review effort [1-5]: 1, Documentation

#462 docs: Add documentation for environment in CLI
  docs/cli/environment.md
Labels: Review effort [1-5]: 2, Documentation

#466 docs: Add documentation for project in CLI
  docs/cli/project.md
Labels: Review effort [1-5]: 2, Documentation

#464 docs: Adding documentation for cli command
  docs/cli/workspace.md
Labels: Review effort [1-5]: 2, Documentation

#465 docs: Added docker support documentation
  docs/contributing-to-keyshade/running-things-locally/docker-support.md
Labels: Review effort [1-5]: 1, Documentation
