Repository keyshade-xyz/keyshade, pull requests merged in 2024-03, with the labels that each got.

#156 feat(auth): Add Google OAuth
  .env.example
  apps/api/package.json
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/controller/auth.controller.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/config/factory/google/google-strategy.factory.spec.ts
  apps/api/src/config/factory/google/google-strategy.factory.ts
  apps/api/src/config/oauth-strategy/google/google.strategy.spec.ts
  apps/api/src/config/oauth-strategy/google/google.strategy.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#158 feat: Add approval support
  .env.example
  README.md
  apps/api/.eslintrc.js
  apps/api/package.json
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/app/app.module.ts
  apps/api/src/approval/approval.e2e.spec.ts
  apps/api/src/approval/approval.module.ts
  apps/api/src/approval/approval.types.ts
  apps/api/src/approval/controller/approval.controller.spec.ts
  apps/api/src/approval/controller/approval.controller.ts
  apps/api/src/approval/service/approval.service.spec.ts
  apps/api/src/approval/service/approval.service.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/controller/auth.controller.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/common/create-approval.ts
  apps/api/src/common/create-event.ts
  apps/api/src/common/get-collective-project-authorities.ts
  apps/api/src/common/get-environment-with-authority.ts
  apps/api/src/common/get-project-with-authority.ts
  apps/api/src/common/get-secret-with-authority.ts
  apps/api/src/common/get-variable-with-authority.ts
  apps/api/src/common/mock-data/workspaces.ts
  apps/api/src/common/workspace-approval-enabled.ts
  apps/api/src/config/factory/google/google-strategy.factory.spec.ts
  apps/api/src/config/factory/google/google-strategy.factory.ts
  apps/api/src/config/oauth-strategy/google/google.strategy.spec.ts
  apps/api/src/config/oauth-strategy/google/google.strategy.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/environment/dto/create.environment/create.environment.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/environment/environment.types.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/prisma/migrations/20240307080842_add_approval/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/project/dto/create.project/create.project.ts
  apps/api/src/project/dto/update.project/update.project.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace-role/workspace-role.types.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  apps/api/src/workspace/dto/create.workspace/create.workspace.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  packages/eslint-config-custom/next.js
Labels: enhancement, bug_fix, Review effort [1-5]: 5

#163 docs: fix typo in environment-variables.md
  docs/contributing-to-keyshade/environment-variables.md
Labels: documentation, Review effort [1-5]: 1

#166 docs(api): Add swagger docs of User Controller
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/common/static.ts
  apps/api/src/main.ts
  apps/api/src/user/controller/user.controller.ts
  apps/api/src/user/dto/create.user/create.user.ts
Labels: documentation, enhancement, Review effort [1-5]: 2

#167 docs(api): Add swagger docs of API key controller
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/controller/api-key.controller.ts
  apps/api/src/api-key/dto/create.api-key/create.api-key.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/common/mock-data/users.ts
Labels: documentation, enhancement, Review effort [1-5]: 2

#168 feat(web): Added waitlist
  apps/web/app/global.css
  apps/web/app/page.tsx
  apps/web/components/killers.tsx
  apps/web/package.json
  apps/web/public/XSVG.svg
  apps/web/public/discordSVG.svg
  apps/web/public/index.ts
  apps/web/public/linkdinSVG (1).svg
  apps/web/src/app/global.css
  apps/web/src/app/layout.tsx
  apps/web/src/app/page.tsx
  apps/web/src/components/killers.tsx
  apps/web/src/components/links.tsx
  apps/web/src/components/ui/encrypt-btn.tsx
  apps/web/src/components/ui/input-spotlight.tsx
  apps/web/src/components/ui/moving-border.tsx
  apps/web/src/utils/cn.ts
  apps/web/tailwind.config.js
Labels: documentation, enhancement, Review effort [1-5]: 4

#169 docs: Remove supabase from docs
  docs/contributing-to-keyshade/design-of-our-code/api.md
  docs/contributing-to-keyshade/environment-variables.md
  docs/contributing-to-keyshade/prerequisites.md
Labels: documentation, Review effort [1-5]: 1

#170 feat(api): Reading `port` Dynamically
  .env.example
  apps/api/Dockerfile
  apps/api/src/main.ts
  docs/contributing-to-keyshade/environment-variables.md
Labels: enhancement, Review effort [1-5]: 2
