Repository keyshade-xyz/keyshade, pull requests merged in 2024-04, with the labels that each got.

#172 [Snyk] Upgrade @million/lint from 0.0.66 to 0.0.73
  package.json
Labels: enhancement, Review effort [1-5]: 1

#173 feat: web docker image optimisation
  apps/web/Dockerfile
  apps/web/next.config.js
  docker-compose-test.yml
  docker-compose.yml
  package.json
Labels: documentation, enhancement, Review effort [1-5]: 2

#175 docs(setup): replace NX with Turbo in setup instructions
  docs/contributing-to-keyshade/setting-things-up.md
Labels: documentation, Review effort [1-5]: 1

#178 fix(web): alignment issue in “Collaboration made easy” section
  apps/web/src/components/colabEasy/index.tsx
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#182 feat(api): Create default workspace on user's creation
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/common/create-user.ts
  apps/api/src/common/create-workspace.ts
  apps/api/src/prisma/migrations/20240413155927_add_default_workspace/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/user/dto/create.user/create.user.ts
  apps/api/src/user/service/user.service.ts
  apps/api/src/user/user.e2e.spec.ts
  apps/api/src/workspace/dto/create.workspace/create.workspace.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  docker-compose-test.yml
Labels: enhancement, Review effort [1-5]: 4

#188 feat(api): Added GitLab OAuth
  .env.example
  apps/api/package.json
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/controller/auth.controller.spec.ts
  apps/api/src/auth/controller/auth.controller.ts
  apps/api/src/config/factory/gitlab/gitlab-strategy.factory.spec.ts
  apps/api/src/config/factory/gitlab/gitlab-strategy.factory.ts
  apps/api/src/config/oauth-strategy/gitlab/gitlab.strategy.spec.ts
  apps/api/src/config/oauth-strategy/gitlab/gitlab.strategy.ts
  docs/contributing-to-keyshade/environment-variables.md
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 3

#189 chore(API): Refactor authority check functions in API
  apps/api/src/approval/controller/approval.controller.spec.ts
  apps/api/src/approval/service/approval.service.spec.ts
  apps/api/src/approval/service/approval.service.ts
  apps/api/src/common/authority-checker.service.ts
  apps/api/src/common/common.module.ts
  apps/api/src/common/get-environment-with-authority.ts
  apps/api/src/common/get-project-with-authority.ts
  apps/api/src/common/get-secret-with-authority.ts
  apps/api/src/common/get-variable-with-authority.ts
  apps/api/src/common/get-workspace-with-authority.ts
  apps/api/src/common/logger.service.ts
  apps/api/src/environment/controller/environment.controller.spec.ts
  apps/api/src/environment/service/environment.service.spec.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/controller/event.controller.spec.ts
  apps/api/src/event/event.module.ts
  apps/api/src/event/service/event.service.spec.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/main.ts
  apps/api/src/project/controller/project.controller.spec.ts
  apps/api/src/project/service/project.service.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/controller/secret.controller.spec.ts
  apps/api/src/secret/service/secret.service.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/socket/change-notifier.socket.ts
  apps/api/src/socket/socket.module.ts
  apps/api/src/variable/controller/variable.controller.spec.ts
  apps/api/src/variable/service/variable.service.spec.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/workspace-role/controller/workspace-role.controller.spec.ts
  apps/api/src/workspace-role/service/workspace-role.service.spec.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace-role/workspace-role.module.ts
  apps/api/src/workspace/controller/workspace.controller.spec.ts
  apps/api/src/workspace/service/workspace.service.spec.ts
  apps/api/src/workspace/service/workspace.service.ts
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#190 feat(api): Added validation for reason field
  apps/api/src/approval/controller/approval.controller.ts
  apps/api/src/common/alphanumeric-reason-pipe.spec.ts
  apps/api/src/common/alphanumeric-reason-pipe.ts
  apps/api/src/environment/controller/environment.controller.ts
  apps/api/src/project/controller/project.controller.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/workspace/controller/workspace.controller.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#193 docs: Update running-the-api.md
  docs/contributing-to-keyshade/running-things-locally/running-the-api.md
Labels: documentation, Review effort [1-5]: 1
