Repository keyshade-xyz/keyshade, pull requests merged in 2025-03, with the labels that each got.

#787 feat(platform): added pagination & loading state for variables page
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/components/dashboard/variable/variableLoader/index.tsx
Labels: Review effort 2/5

#804 feat(platform): added loading state to add secret dialog & disabled input fields
  apps/platform/src/components/dashboard/secret/addSecretDialogue/index.tsx
  apps/platform/src/hooks/use-http.ts
Labels: Review effort 2/5

#809 feat(platform): Add pagination & loading more functionality for secrets page
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/lib/constants.ts
Labels: Review effort 2/5

#726 feat(platform): Create and Delete API Keys
  apps/platform/components.json
  apps/platform/public/svg/shared/crown.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/components/common/authority-selector.tsx
  apps/platform/src/components/common/copy-to-clipboard.tsx
  apps/platform/src/components/common/slug.tsx
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
  apps/platform/src/components/dashboard/secret/addSecretDialogue/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/userProfile/apiKeys/addApiKeyDialog/index.tsx
  apps/platform/src/components/userProfile/apiKeys/apiKeyCard/index.tsx
  apps/platform/src/components/userProfile/apiKeys/confirmDeleteApiKey/index.tsx
  apps/platform/src/hooks/use-http.ts
  apps/platform/src/lib/constants.ts
  apps/platform/src/lib/controller-instance.ts
  apps/platform/src/store/index.ts
  apps/platform/tailwind.config.ts
  apps/platform/tsconfig.json
  packages/api-client/src/index.ts
  packages/schema/src/api-key/index.ts
  packages/schema/src/enums/index.ts
  packages/schema/src/enums/index.types.ts
  packages/schema/src/index.types.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/enums.test.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#812 chore(api): Add extensive logging
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/auth/authorization.types.ts
  apps/api/src/auth/service/auth.service.ts
  apps/api/src/auth/service/authority-checker.service.ts
  apps/api/src/auth/service/authorization.service.ts
  apps/api/src/cache/cache.service.ts
  apps/api/src/common/collective-authorities.ts
  apps/api/src/common/environment.ts
  apps/api/src/common/event.ts
  apps/api/src/common/redirect.ts
  apps/api/src/common/secret.ts
  apps/api/src/common/user.ts
  apps/api/src/common/util.ts
  apps/api/src/common/variable.ts
  apps/api/src/common/workspace.ts
  apps/api/src/config/factory/github/github-strategy.factory.ts
  apps/api/src/config/factory/gitlab/gitlab-strategy.factory.ts
  apps/api/src/config/factory/google/google-strategy.factory.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/event/service/event.service.ts
  apps/api/src/feedback/service/feedback.service.ts
  apps/api/src/integration/plugins/discord/discord.integration.ts
  apps/api/src/integration/plugins/slack/slack.integration.ts
  apps/api/src/integration/service/integration.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/main.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/secret.types.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/socket/change-notifier.socket.ts
  apps/api/src/user/service/user.service.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.types.ts
  apps/api/src/workspace-role/controller/workspace-role.controller.ts
  apps/api/src/workspace-role/service/workspace-role.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace/service/workspace.service.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
Labels: Review effort 3/5

#813 chore(api): Add suggestions from #812
  apps/api/src/auth/service/authority-checker.service.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/service/secret.service.ts
Labels: Review effort 2/5

#814 refactor(platform): Reorganized user profile components
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/components/common/input-loading.tsx
  apps/platform/src/components/userSettings/apiKeys/addApiKeyDialog/index.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeyCard/index.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeySection/index.tsx
  apps/platform/src/components/userSettings/apiKeys/confirmDeleteApiKey/index.tsx
  apps/platform/src/components/userSettings/profile/deleteProfile/index.tsx
  apps/platform/src/components/userSettings/profile/emailSettings/index.tsx
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
  apps/platform/src/hooks/use-http.ts
  packages/schema/src/enums/index.ts
  packages/schema/src/enums/index.types.ts
  packages/schema/src/user/index.ts
  packages/schema/tests/auth.spec.ts
  packages/schema/tests/user.spec.ts
  packages/schema/tests/workspace-membership.spec.ts
Labels: Review effort 3/5

#815 feat(platform): Edit API keys in the user settings
  apps/platform/src/components/common/authority-selector.tsx
  apps/platform/src/components/userSettings/apiKeys/addApiKeyDialog/index.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeyCard/index.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeySection/index.tsx
  apps/platform/src/components/userSettings/apiKeys/editApiKeySheet/index.tsx
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
Labels: Review effort 3/5

#817 fix(platfrom): navigation tab render bug
  apps/platform/src/components/shared/navbar/index.tsx
Labels: Review effort 2/5

#819 feat(platform): Delete account in user settings
  apps/platform/src/components/userSettings/profile/deleteProfile/index.tsx
  apps/platform/src/components/userSettings/profile/deleteProfileDialog/index.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 2/5

#823 feat(platform): Add dialog for viewing and downloading project keys
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/viewAndDownloadKeysDialog/index.tsx
  apps/platform/src/components/shared/dashboard/hidden-content.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 2/5

#826 feat(platform): Ability to view secret and variable versions
  api-collection/Secret Controller/Get all revisions of secret.bru
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/variable.service.ts
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/components/common/avatar.tsx
  apps/platform/src/components/dashboard/secret/editSecretSheet/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/secret/secretRevisionSheet/index.tsx
  apps/platform/src/components/dashboard/variable/addVariableDialogue/index.tsx
  apps/platform/src/components/dashboard/variable/editVariableSheet/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableRevisionsSheet/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/lib/utils.ts
  apps/platform/src/store/index.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
  packages/schema/tests/secret.spec.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#827 feat(platform): added pagination for environments screen
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/components/dashboard/environment/environmentLoader/index.tsx
Labels: Review effort 2/5

#825 feat(platform): Ability to reveal value of secret
  apps/platform/package.json
  apps/platform/public/svg/shared/eye-slash.svg
  apps/platform/public/svg/shared/eye.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/info.svg
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/components/dashboard/secret/addSecretDialogue/index.tsx
  apps/platform/src/components/dashboard/secret/decryptSecret/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/ui/tooltip.tsx
  apps/platform/src/lib/decrypt.ts
  apps/platform/src/store/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5

#833 feat(api): Return tier limit for entities in projects and workspaces
  apps/api/src/common/tier-limit.service.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/project.service.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  apps/api/src/workspace/workspace.service.ts
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/store/index.ts
  packages/schema/src/project/index.ts
  packages/schema/src/project/index.types.ts
  packages/schema/src/workspace/index.ts
  packages/schema/src/workspace/index.types.ts
  packages/schema/tests/project.spec.ts
  packages/schema/tests/workspace.spec.ts
Labels: Review effort 3/5

#832 fix(platform): ui issues on otp & session expiry toasts
  apps/platform/src/app/auth/otp/page.tsx
  apps/platform/src/hooks/use-http.ts
Labels: Review effort 2/5

#820 fix(web): Add margin for different screen size
  apps/web/src/components/secretSection/index.tsx
Labels: Review effort 1/5

#840 fix(platform): redirect to dashboard after updating profile details
  apps/platform/src/app/auth/account-details/page.tsx
Labels: Review effort 1/5

#831 feat(platform): Create roles
  apps/api/src/workspace-role/workspace-role.service.ts
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/minus-square.svg
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/common/authority-selector.tsx
  apps/platform/src/components/roles/createRolesDialog/index.tsx
  apps/platform/src/components/userSettings/apiKeys/addApiKeyDialog/index.tsx
  apps/platform/src/components/userSettings/apiKeys/editApiKeySheet/index.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 3/5

#808 feat(platform): Added workspace settings page
  .github/workflows/validate-schema.yaml
  apps/api/src/auth/service/authority-checker.service.ts
  apps/api/src/auth/service/authorization.service.ts
  apps/api/src/common/workspace.ts
  apps/api/src/workspace/workspace.service.ts
  apps/api/src/workspace/workspace.types.ts
  apps/platform/package.json
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
  apps/platform/src/app/(main)/(settings)/[workspace]/settings/page.tsx
  apps/platform/src/components/dashboard/environment/emptyEnvironmentListContent/index.tsx
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
  apps/platform/src/components/dashboard/workspace/confirmDeleteWorkspace/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/lib/utils.ts
  apps/platform/src/store/index.ts
  package.json
  packages/schema/package.json
  packages/schema/src/workspace/index.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/auth.spec.ts
  packages/schema/tests/enums.test.ts
  packages/schema/tests/environment.spec.ts
  packages/schema/tests/event.spec.ts
  packages/schema/tests/integration.spec.ts
  packages/schema/tests/pagination.spec.ts
  packages/schema/tests/project.spec.ts
  packages/schema/tests/secret.spec.ts
  packages/schema/tests/user.spec.ts
  packages/schema/tests/variable.spec.ts
  packages/schema/tests/workspace-membership.spec.ts
  packages/schema/tests/workspace-role.spec.ts
  packages/schema/tests/workspace.spec.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#841 refactor(platform): update auth provider card in profile settings
  apps/platform/public/svg/auth/emailWhiteSVG.svg
  apps/platform/public/svg/auth/githubWhiteSVG.svg
  apps/platform/public/svg/auth/gitlabWhiteSVG.svg
  apps/platform/public/svg/auth/googleWhiteSVG.svg
  apps/platform/public/svg/auth/index.ts
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/components/userSettings/profile/authProvider/index.tsx
  apps/platform/src/components/userSettings/profile/authProviderCard/index.tsx
  apps/platform/src/components/userSettings/profile/emailSettings/index.tsx
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
Labels: Review effort 2/5

#842 feat(api): Return workspace membership creation date
  apps/api/src/workspace-membership/workspace-membership.service.ts
  packages/schema/src/workspace-membership/index.ts
Labels: Review effort 1/5

#845 fix(platform): Added profile picture in the user settings with proper fallback
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
Labels: Review effort 1/5

#799 feat(platform): One-Time Secret Display for API Key (#771)
  apps/platform/src/components/userSettings/apiKeys/addApiKeyDialog/index.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeyOneTimeDisplayDialog/index.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 2/5

#849 feat(api): add database seeding script and related commands
  apps/api/package.json
  apps/api/src/prisma/seed.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#848 feat(platform): add environment management to project creation dialog
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
Labels: Review effort 2/5

#850 feat(api): Resend workspace invitation
  api-collection/Workspace Membership Controller/Resend invitation.bru
  apps/api/src/workspace-membership/workspace-membership.controller.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace-membership/workspace-membership.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace-role/workspace-role.service.ts
  packages/api-client/src/controllers/workspace-membership.ts
  packages/schema/src/workspace-membership/index.ts
  packages/schema/src/workspace-membership/index.types.ts
  packages/schema/src/workspace-role/index.ts
Labels: Review effort 2/5
