Repository keyshade-xyz/keyshade, pull requests merged in 2025-02, with the labels that each got.

#665 feat(api): Workspace-membership invitationAccepted included
  apps/api/src/workspace-membership/service/workspace-membership.service.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
Labels: Review effort [1-5]: 1

#660 fix(api): Project hard sync existing entities deleted
  apps/api/src/project/service/project.service.ts
  docs/cli/project.md
Labels: Review effort [1-5]: 2

#686 feat: Update details in listing secrets
  api-collection/Secret Controller/Fetch all by project and environment.bru
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/secret.command.ts
  apps/cli/src/commands/secret/create.secret.ts
  apps/cli/src/commands/secret/delete.secret.ts
  apps/cli/src/commands/secret/get.secret.ts
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/secret/update.secret.ts
  apps/cli/src/util/date-formatter.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/tests/secret.spec.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/tests/secret.spec.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 3

#684 feat(platform): Edit secret in your project
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/components/dashboard/secret/editSecretSheet/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
Labels: Review effort [1-5]: 3

#688 fix(platform): ContextMenu not working on variable card
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
Labels: Review effort [1-5]: 1

#689 feat(platform): Add Google OAuth
  apps/api/src/common/redirect.ts
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/auth/account-details/page.tsx
  apps/platform/src/app/auth/otp/page.tsx
  apps/platform/src/app/auth/page.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/store/index.ts
  packages/api-client/src/controllers/auth.ts
  packages/schema/src/auth/index.ts
  packages/schema/src/auth/index.types.ts
  packages/schema/tests/auth.spec.ts
Labels: Review effort [1-5]: 4

#690 refactor(platform): Updated the secret table and changed edit variable dialog to a sheet
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/components/dashboard/secret/editSecretSheet/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/editVariableSheet/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
Labels: Review effort [1-5]: 2

#692 fix(api): Github OAuth redirect not working
  apps/api/src/auth/controller/auth.controller.ts
Labels: Review effort [1-5]: 1

#720 chore(docs): Added section for building packages
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  docs/contributing-to-keyshade/setting-things-up.md
  package.json
Labels: Review effort [1-5]: 2

#723 fix(platform): Fixed the typo in query params
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
Labels: Review effort [1-5]: 1

#735 feat: Variables listing revamp
  api-collection/Variable Controller/Fetch all by project and environment.bru
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/secret/create.secret.ts
  apps/cli/src/commands/variable.command.ts
  apps/cli/src/commands/variable/create.variable.ts
  apps/cli/src/commands/variable/delete.variable.ts
  apps/cli/src/commands/variable/get.variable.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/variable/revisions.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/variable/update.variable.ts
  packages/api-client/src/controllers/variable.ts
  packages/api-client/tests/variable.spec.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
  packages/schema/tests/variable.spec.ts
Labels: Review effort [1-5]: 4

#734 feat(platform): extract copyToClipboad into reusable util
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/lib/clipboard.ts
Labels: Review effort [1-5]: 2

#724 fix(ui): Adjust grid layout for environment cards
  apps/platform/src/components/common/slug.tsx
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
Labels: Review effort [1-5]: 1

#736 fix(platform): Follow-up for remaining changes from PR #724
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
Labels: Review effort [1-5]: 1

#741 chore(api): add SMTP_SECURE environment variable to Mail Service
  .env.example
  apps/api/src/common/env/env.schema.ts
  apps/api/src/mail/services/mail.service.ts
  docs/contributing-to-keyshade/environment-variables.md
Labels: Review effort [1-5]: 1

#738 fix(api): Secrets with empty names
  apps/api/src/decorators/trim-string.decorator.ts
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.e2e.spec.ts
Labels: Review effort [1-5]: 2

#683 feat(platform): Add workspace slug for projects in url
  apps/api/src/secret/secret.e2e.spec.ts
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/components/common/slug.tsx
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
Labels: Review effort [1-5]: 4

#749 feat(platform): add roles tab in sidebar
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/roles.svg
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
Labels: Review effort [1-5]: 1

#746 chore: lint-staged configured
  .gitignore
  .husky/pre-commit
  apps/api/src/secret/dto/create.secret/create.secret.ts
  lint-staged.config.js
  package.json
  pnpm-lock.yaml
Labels: Review effort [1-5]: 2

#745 fix(api): Variables with empty names
  apps/api/src/decorators/non-empty-trimmed-string.decorator.ts
  apps/api/src/decorators/trim-string.decorator.ts
  apps/api/src/decorators/trimmed-string.decorator.ts
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/variable/dto/create.variable/create.variable.ts
  apps/api/src/variable/variable.e2e.spec.ts
Labels: Review effort [1-5]: 2

#757 fix(api): Release workflow node 22.x
  .github/workflows/release.yml
Labels: Review effort 1/5

#759 fix: Avoid toast duplication & added optional description
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/lib/clipboard.ts
Labels: Review effort 2/5

#767 feat(platform): Add copy to clipboard functionality for secret slug
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
Labels: Review effort 1/5

#766 feat(platform): Add checkmark icon to copy slug button for environments (#742)
  apps/platform/public/svg/shared/checkmark.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/src/components/common/slug.tsx
Labels: Review effort 1/5

#763 chore: Issue PR reminder workflow created
  .github/workflows/auto-assign.yaml
  .github/workflows/issue-pr-reminder.yaml
  .github/workflows/issue-unassign.yaml
  .github/workflows/pr-close.yaml
  .github/workflows/pr-review-reminder.yaml
Labels: Review effort 4/5

#769 feat(platform): Add copy slug functionality to variable card context menu
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
Labels: Review effort 1/5

#751 refactor(platform): Added avatars on secret and variable accordions
  apps/platform/src/components/common/avatar.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  packages/schema/src/secret/index.ts
  packages/schema/src/variable/index.ts
  packages/schema/tests/secret.spec.ts
  packages/schema/tests/variable.spec.ts
Labels: Review effort [1-5]: 1

#774 feat(platform): Add copy to clipboard functionality for project slug
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
  apps/platform/src/lib/clipboard.ts
Labels: Review effort 2/5

#778 fix(platform): Fixed infinite API calls bug
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/hooks/use-http.ts
Labels: Review effort 2/5

#782 feat(platform): Displays a warning message when store private key switch is ON
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
Labels: Review effort 2/5

#788 fix(api): Issue fetched via API
  .github/workflows/auto-assign.yaml
Labels: Review effort 2/5

#789 fix(api): added import statement for crypto module
  apps/api/src/common/util.ts
Labels: Review effort 1/5

#791 fix(web): Misalignment of toast message after joining the waitlist
  apps/web/src/components/hero/index.tsx
Labels: Review effort 1/5

#800 fix(api): Issue with authorities and expiry field update in API Key
  api-collection/Api Key Controller/Update API key.bru
  apps/api/src/api-key/dto/create.api-key/create.api-key.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/common/util.ts
Labels: Review effort 2/5

#797 feat(cli): Error message formatted
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/environment/create.environment.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/environment/get.environment.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/environment/update.environment.ts
  apps/cli/src/commands/project/create.project.ts
  apps/cli/src/commands/project/delete.project.ts
  apps/cli/src/commands/project/fork.project.ts
  apps/cli/src/commands/project/get.project.ts
  apps/cli/src/commands/project/list-forks.project.ts
  apps/cli/src/commands/project/list.project.ts
  apps/cli/src/commands/project/sync.project.ts
  apps/cli/src/commands/project/unlink.project.ts
  apps/cli/src/commands/project/update.project.ts
  apps/cli/src/commands/secret/create.secret.ts
  apps/cli/src/commands/secret/delete.secret.ts
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/secret/update.secret.ts
  apps/cli/src/commands/variable/create.variable.ts
  apps/cli/src/commands/variable/delete.variable.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/variable/revisions.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/variable/update.variable.ts
  apps/cli/src/commands/workspace/create.workspace.ts
  apps/cli/src/commands/workspace/delete.workspace.ts
  apps/cli/src/commands/workspace/export.workspace.ts
  apps/cli/src/commands/workspace/get.workspace.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/commands/workspace/membership/accept-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/cancel-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/decline-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/get-all-members.membership.ts
  apps/cli/src/commands/workspace/membership/invite.membership.ts
  apps/cli/src/commands/workspace/membership/leave.membership.ts
  apps/cli/src/commands/workspace/membership/remove.membership.ts
  apps/cli/src/commands/workspace/membership/transfer-ownership.membership copy.ts
  apps/cli/src/commands/workspace/membership/update-role.membership.ts
  apps/cli/src/commands/workspace/role/create.role.ts
  apps/cli/src/commands/workspace/role/delete.role.ts
  apps/cli/src/commands/workspace/role/get.role.ts
  apps/cli/src/commands/workspace/role/list.role.ts
  apps/cli/src/commands/workspace/role/update.role.ts
  apps/cli/src/commands/workspace/search.workspace.ts
  apps/cli/src/commands/workspace/update.workspace.ts
Labels: Review effort 2/5

#798 fix: Added back missing endpoints
  api-collection/Secret Controller/Fetch all by project and environment.bru
  api-collection/Variable Controller/Fetch all by project and environment.bru
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/service/project.service.ts
  apps/api/src/secret/controller/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
  apps/api/src/variable/controller/variable.controller.ts
  apps/api/src/variable/service/variable.service.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/cli/src/commands/run.command.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/variable.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
Labels: Review effort 4/5

#796 feat(platform): update Combobox to add new workspace to state
  apps/platform/src/components/ui/combobox.tsx
Labels: Review effort 1/5

#802 fix(api): Forks asynchronous filter fixed
  apps/api/src/project/service/project.service.ts
Labels: Review effort 2/5

#805 fix(cli/api): eccrypto loaded dynamically
  apps/api/src/common/cryptography.ts
  apps/cli/src/util/decrypt.ts
Labels: Review effort 1/5
