Repository keyshade-xyz/keyshade, pull requests merged in 2025-06, with the labels that each got.

#983 fix(platform): Suspense boundary fix
  apps/platform/src/app/layout.tsx
Labels: Review effort 1/5

#978 feat(api): added support for email preferences
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/common/user.ts
  apps/api/src/environment/environment.e2e.spec.ts
  apps/api/src/event/event.e2e.spec.ts
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/prisma/migrations/20250518092245_add_email_preference_model/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/user/dto/update.user/update.user.ts
  apps/api/src/user/user.service.ts
  apps/api/src/user/user.types.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
  apps/api/src/workspace-membership/workspace-membership.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace/workspace.e2e.spec.ts
  packages/schema/src/user/index.ts
Labels: Review effort 2/5

#990 feat(api): Encrypt integration metadata at rest
  .env.example
  apps/api/package.json
  apps/api/src/common/cryptography.ts
  apps/api/src/common/env/env.schema.ts
  apps/api/src/common/event.ts
  apps/api/src/integration/integration.service.ts
  apps/api/src/prisma/migrations/20250607075155_update_integration_metadata_field/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/platform/src/app/(main)/integrations/@details/page.tsx
  apps/platform/src/components/posthog-provider.tsx
  docs/contributing-to-keyshade/environment-variables.md
Labels: Review effort 3/5

#995 refactor(auth): improve OTP and email validation in form
  apps/platform/src/components/auth/auth-email-form.tsx
  apps/platform/src/components/auth/otp/otp-input-form.tsx
  apps/platform/src/lib/is-email-valid.ts
  apps/platform/src/lib/is-empty-string.ts
Labels: Review effort 2/5

#1005 Revert "refactor(auth): improve OTP and email validation in form"
  apps/platform/src/components/auth/auth-email-form.tsx
  apps/platform/src/components/auth/otp/otp-input-form.tsx
  apps/platform/src/lib/is-email-valid.ts
  apps/platform/src/lib/is-empty-string.ts
Labels: Review effort 2/5

#981 feat: Add Secret & Variable export, include JSON format
  apps/api/src/project/export/export.service.ts
  apps/api/src/project/export/export.spec.ts
  apps/api/src/project/export/export.types.ts
  apps/api/src/project/project.controller.ts
  apps/api/src/project/project.e2e.spec.ts
  apps/api/src/project/project.module.ts
  apps/api/src/project/project.service.ts
  apps/api/src/project/project.types.ts
  apps/api/src/secret/secret.module.ts
  apps/api/src/variable/variable.module.ts
  apps/cli/src/commands/project.command.ts
  apps/cli/src/commands/project/export.project.ts
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/store/index.ts
  packages/api-client/src/controllers/project.ts
  packages/schema/src/project/index.ts
  packages/schema/src/project/index.types.ts
Labels: Review effort 4/5

#1013 feat(api): Add onboarding answers and referral logic
  apps/api/src/common/user.ts
  apps/api/src/common/util.ts
  apps/api/src/feedback/feedback.e2e.spec.ts
  apps/api/src/prisma/migrations/20250617150502_referral_code_and_onboarding_answers/migration.sql
  apps/api/src/prisma/prisma.repository.ts
  apps/api/src/prisma/schema.prisma
  apps/api/src/prisma/seed.ts
  apps/api/src/user/dto/onboarding-answers/onboarding-answers.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.e2e.spec.ts
  apps/api/src/user/user.service.ts
  packages/api-client/src/controllers/user.ts
  packages/schema/src/user/index.ts
  packages/schema/src/user/index.types.ts
Labels: Review effort 3/5

#1022 docs: small edits and spelling checks
  docs/getting-started/add-keyshade-to-your-project.md
  docs/getting-started/installing-the-cli.md
  docs/getting-started/running-your-app.md
Labels: Review effort 1/5

#1018 feat(platform): onboarding-marketing question update & share referral
  apps/api/src/common/user.ts
  apps/api/src/common/util.ts
  apps/api/src/feedback/feedback.e2e.spec.ts
  apps/api/src/prisma/migrations/20250617150502_referral_code_and_onboarding_answers/migration.sql
  apps/api/src/prisma/migrations/20250620073704_remove_would_like_to_refer_field_onboarding_question/migration.sql
  apps/api/src/prisma/prisma.repository.ts
  apps/api/src/prisma/schema.prisma
  apps/api/src/prisma/seed.ts
  apps/api/src/user/dto/onboarding-answers/onboarding-answers.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.e2e.spec.ts
  apps/api/src/user/user.service.ts
  apps/platform/next.config.ts
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/app/auth/account-details/page.tsx
  apps/platform/src/components/auth/account-details/account-details-form.tsx
  apps/platform/src/components/auth/account-details/onboarding slides/profile-details-form.tsx
  apps/platform/src/components/auth/account-details/onboarding slides/referral-details-form.tsx
  apps/platform/src/components/auth/account-details/onboarding slides/role-industry-form.tsx
  apps/platform/src/components/auth/account-details/onboarding slides/team-overview-form.tsx
  apps/platform/src/components/auth/account-details/onboarding-stepper.tsx
  apps/platform/src/components/shared/navbar/profile-menu.tsx
  apps/platform/src/components/ui/select.tsx
  apps/platform/src/components/ui/stepper.tsx
  apps/platform/src/components/userSettings/profile/authProvider/index.tsx
  apps/platform/src/components/userSettings/profile/emailSettings/index.tsx
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
  apps/platform/src/components/userSettings/profile/shareReferralCode/index.tsx
  packages/api-client/src/controllers/user.ts
  packages/schema/src/user/index.ts
  packages/schema/src/user/index.types.ts
Labels: Review effort 3/5

#1025 feat(cli): Select secret-variable while Project Import command
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/project/import.project.ts
Labels: Review effort 2/5

#1006 [WIP] feat: Add vercel integration
  apps/api/package.json
  apps/api/src/auth/service/authority-checker.service.ts
  apps/api/src/common/dto/entry.dto.ts
  apps/api/src/common/event.ts
  apps/api/src/common/util.ts
  apps/api/src/event/event.types.ts
  apps/api/src/integration/dto/create.integration/create.integration.ts
  apps/api/src/integration/integration.controller.ts
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/integration/integration.service.ts
  apps/api/src/integration/integration.types.ts
  apps/api/src/integration/plugins/base.integration.ts
  apps/api/src/integration/plugins/discord.integration.ts
  apps/api/src/integration/plugins/integration.factory.ts
  apps/api/src/integration/plugins/slack.integration.ts
  apps/api/src/integration/plugins/vercel.integration.ts
  apps/api/src/prisma/migrations/20250610111838_add_vercel/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/dto/create.secret/create.secret.ts
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/variable.service.ts
  apps/api/tsconfig.json
  packages/schema/src/integration/index.ts
  pnpm-lock.yaml
Labels: Possible security concern, Review effort 4/5

#1036 feat(platform): integration setup private key
  apps/api/src/common/environment.ts
  apps/api/src/common/slug-generator.service.ts
  apps/api/src/event/event.types.ts
  apps/api/src/integration/dto/create.integration/create.integration.ts
  apps/api/src/integration/dto/update.integration/update.integration.ts
  apps/api/src/integration/integration.controller.ts
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/integration/integration.service.ts
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/variable.service.ts
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@overview/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/integrations/@setup/page.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/index.tsx
  apps/platform/src/components/dashboard/secret/editSecretSheet/index.tsx
  apps/platform/src/components/integrations/ProjectEnvironmentMapping/index.tsx
  apps/platform/src/components/integrations/projectEnvironmentInput/index.tsx
  apps/platform/src/components/integrations/updateIntegrationSheet/index.tsx
  apps/platform/src/hooks/use-fetch-privatekey.ts
  packages/common/src/integration.ts
  packages/schema/src/integration/index.ts
Labels: Possible security concern, Review effort 3/5
