Repository keyshade-xyz/keyshade, pull requests merged in 2025-01, with the labels that each got.

#591 feat(platform): Show all the existing variables inside a project
  apps/platform/public/svg/shared/Error.svg
  apps/platform/public/svg/shared/Vector.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/message.svg
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/project/[project]/layout.tsx
  apps/platform/src/components/dashboard/projectCard/index.tsx
  apps/platform/src/components/ui/collapsible.tsx
  apps/platform/src/components/ui/textarea.tsx
  erDetails(userData)
  packages/api-client/src/core/response-parser.ts
Labels: Review effort [1-5]: 4

#594 feat(cli): Add import sub commmand for project.
  apps/cli/package.json
  apps/cli/src/commands/project.command.ts
  apps/cli/src/commands/project/import.project.ts
  apps/cli/src/commands/scan.command.ts
  packages/secret-scan/src/index.ts
  packages/secret-scan/src/test/scan-js-object.test.ts
  packages/secret-scan/src/types/index.d.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 3

#609 feat(api): Add ADMIN authority for API keys
  .github/workflows/validate-api.yaml
  apps/api/src/auth/guard/api-key/api-key.guard.ts
  apps/api/src/prisma/migrations/20250109110640_add_admin_api_key_authority/migration.sql
  apps/api/src/prisma/schema.prisma
Labels: Review effort [1-5]: 2

#612 feat(schema): Add workspace invitation schema
  packages/schema/src/workspace/index.ts
  packages/schema/src/workspace/index.types.ts
  packages/schema/tests/workspace.spec.ts
Labels: Review effort [1-5]: 2

#615 refactor(cli): Replace arguments with options
  apps/cli/CHANGELOG.md
  apps/cli/package-lock.json
  apps/cli/package.json
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/variable/revisions.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/workspace/membership/cancel-invitation.membership.ts
  apps/cli/src/commands/workspace/membership/invite.membership.ts
  apps/cli/src/commands/workspace/membership/remove.membership.ts
  apps/cli/src/commands/workspace/membership/transfer-ownership.membership copy.ts
  apps/cli/src/commands/workspace/membership/update-role.membership.ts
  apps/cli/src/commands/workspace/role.workspace.ts
  apps/cli/src/commands/workspace/role/create.role.ts
  apps/cli/src/commands/workspace/role/update.role.ts
Labels: Review effort [1-5]: 2

#603 feat(platform): Add a new secret and added loader on project screen
  apps/platform/.eslintrc.cjs
  apps/platform/package.json
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/trash.svg
  apps/platform/public/svg/shared/vector.svg
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/project/[project]/layout.tsx
  apps/platform/src/components/common/online-status-handler.tsx
  apps/platform/src/components/ui/add-secret-dialog.tsx
  apps/platform/src/components/ui/alert-dialog.tsx
  apps/platform/src/components/ui/collapsible.tsx
  apps/platform/src/components/ui/confirm-delete.tsx
  apps/platform/src/components/ui/edit-variable-dialog.tsx
  apps/platform/src/components/ui/project-screen-loader.tsx
  apps/platform/src/hooks/use-online-status.ts
  apps/web/src/components/hero/index.tsx
  apps/web/src/components/pricing/card/index.tsx
  pnpm-lock.yaml
Labels: Review effort [1-5]: 4

#602 feat(platform): Edit existing variables in a project
  apps/platform/package.json
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/components/ui/collapsible.tsx
  apps/platform/src/components/ui/confirm-delete.tsx
  apps/platform/src/components/ui/edit-variable-dialog.tsx
  pnpm-lock.yaml
Labels: Review effort [1-5]: 4

#593 feat(platform): Add new variables to a project
  apps/platform/src/app/(main)/project/[project]/layout.tsx
Labels: Review effort [1-5]: 3

#531 feat(api): Add slack integration
  apps/api/package-lock.json
  apps/api/package.json
  apps/api/pnpm-lock.yaml
  apps/api/src/integration/integration.types.ts
  apps/api/src/integration/plugins/factory/integration.factory.ts
  apps/api/src/integration/plugins/slack/slack.integration.spec.ts
  apps/api/src/integration/plugins/slack/slack.integration.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 3

#600 feat(platform): Delete variable from a project
  pnpm-lock.yaml
Labels: Review effort [1-5]: 4

#619 feat(api-client): Get all workspace invitation
  packages/api-client/src/controllers/workspace.ts
  packages/api-client/tests/workspace.spec.ts
Labels: Review effort [1-5]: 2

#626 refactor(platform): Refactor project components
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/editProjectSheet/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/store/index.ts
  apps/platform/src/store/workspace.ts
Labels: Review effort [1-5]: 3

#634 feat(cli): supports to specify environment(s) and its optional description
  apps/cli/src/commands/project/create.project.ts
Labels: Review effort [1-5]: 2

#636 fix(cli): Check for .keyshade dir if profile isn't found
  apps/cli/src/util/configuration.ts
Labels: Review effort [1-5]: 1

#641 fix(cli): Add keywords for improved package discoverability
  apps/cli/package.json
Labels: Review effort [1-5]: 1

#639 fix(cli): Profile name now can use - and _ and updated error message
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/profile/create.profile.ts
Labels: Review effort [1-5]: 1

#638 fix(cli): Create project --store-private-key option default value removed
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/project/create.project.ts
Labels: Review effort [1-5]: 1

#644 feat(cli): update README with feature and installation
  apps/cli/README.md
Labels: Review effort [1-5]: 1

#640 fix: (cli) Prompt users for all values if no option set and show default values
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/profile/create.profile.ts
Labels: Review effort [1-5]: 2

#645 feat(cli): Api health probe
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/base.command.ts
  apps/cli/src/commands/environment/create.environment.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/environment/get.environment.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/environment/update.environment.ts
  apps/cli/src/commands/project/create.project.ts
  apps/cli/src/commands/project/delete.project.ts
  apps/cli/src/commands/project/fork.project.ts
  apps/cli/src/commands/project/get.project.ts
  apps/cli/src/commands/project/list-forks.project.ts
  apps/cli/src/commands/project/list.project.ts
  apps/cli/src/commands/project/sync.project.ts
  apps/cli/src/commands/project/unlink.project.ts
  apps/cli/src/commands/project/update.project.ts
  apps/cli/src/commands/secret/create.secret.ts
  apps/cli/src/commands/secret/delete.secret.ts
  apps/cli/src/commands/secret/get.secret.ts
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
  apps/cli/src/commands/secret/rollback.secret.ts
  apps/cli/src/commands/secret/update.secret.ts
  apps/cli/src/commands/variable/create.variable.ts
  apps/cli/src/commands/variable/delete.variable.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/variable/revisions.variable.ts
  apps/cli/src/commands/variable/rollback.variable.ts
  apps/cli/src/commands/variable/update.variable.ts
  apps/cli/src/commands/workspace/create.workspace.ts
  apps/cli/src/commands/workspace/delete.workspace.ts
  apps/cli/src/commands/workspace/export.workspace.ts
  apps/cli/src/commands/workspace/get.workspace.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/commands/workspace/membership/get-all-members.membership.ts
  apps/cli/src/commands/workspace/role/create.role.ts
  apps/cli/src/commands/workspace/role/delete.role.ts
  apps/cli/src/commands/workspace/role/get.role.ts
  apps/cli/src/commands/workspace/role/list.role.ts
  apps/cli/src/commands/workspace/role/update.role.ts
  apps/cli/src/commands/workspace/search.workspace.ts
  apps/cli/src/commands/workspace/update.workspace.ts
  apps/cli/src/util/controller-instance.ts
  packages/api-client/src/controllers/app.ts
  packages/api-client/src/index.ts
Labels: Review effort [1-5]: 3

#649 feat(web): Add Google Analytics integration
  apps/web/package.json
  apps/web/src/app/layout.tsx
  apps/web/src/env.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 1

#633 feat(cli): Add List-invitation command
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/workspace.command.ts
  apps/cli/src/commands/workspace/list-invitations.workspace.ts
Labels: Review effort [1-5]: 2

#652 feat(api): Secret rotation
  apps/api/src/common/secret.spec.ts
  apps/api/src/common/secret.ts
  apps/api/src/common/util.ts
  apps/api/src/prisma/migrations/20250123150220_add_rotate_after_in_secret/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/service/secret.service.ts
Labels: Review effort [1-5]: 3

#647 fix(api): Only user's default workspace returns isDefault: true
  apps/api/src/workspace/service/workspace.service.ts
Labels: Review effort [1-5]: 2

#655 feat(platform): Improved UI of secret listing
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
Labels: Review effort [1-5]: 2

#648 fix(cli): Workspace membership API client payload fixed (#614)
  packages/api-client/src/controllers/workspace-membership.ts
Labels: Review effort [1-5]: 1

#661 refactor(layout): Refactor layout structure to improve Navbar positioning & child component
  apps/platform/src/app/(main)/layout.tsx
  apps/platform/src/app/(main)/settings/@profile/page.tsx
Labels: Review effort [1-5]: 2

#671 feat(platform): Implement delete project
  apps/platform/src/app/(main)/layout.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/components/dashboard/project/confirmDeleteProject/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
Labels: Review effort [1-5]: 3

#677 feat(platform): Add CopySVG icon to the Slug component and update imports
  apps/platform/public/svg/shared/copy.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/src/components/common/slug.tsx
Labels: Review effort [1-5]: 1

#676 feat(platform): update table ui and change variable to accordion
  apps/platform/src/app/(main)/project/[project]/@variable/page.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
Labels: Review effort [1-5]: 2

#678 feat(platform): Add new access level SVGs and integrate into ProjectCard component
  apps/platform/public/svg/dashboard/global.svg
  apps/platform/public/svg/dashboard/index.ts
  apps/platform/public/svg/dashboard/internal.svg
  apps/platform/public/svg/dashboard/private.svg
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
Labels: Review effort [1-5]: 2

#679 fix(cli): Version flag causing errors
  apps/cli/CHANGELOG.md
  apps/cli/src/index.ts
Labels: Review effort [1-5]: 1

#674 feat(platform): Added the feature for deleting a secret
  apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
  apps/platform/src/components/dashboard/secret/confirmDeleteSecret/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
Labels: Review effort [1-5]: 3, Possible security concern

#680 feat(api, schema): Add preview field in API Key
  apps/api/src/api-key/api-key.e2e.spec.ts
  apps/api/src/api-key/service/api-key.service.ts
  apps/api/src/environment/service/environment.service.ts
  apps/api/src/prisma/migrations/20250130160517_add_preview_in_api_key/migration.sql
  apps/api/src/prisma/schema.prisma
  packages/schema/src/api-key/index.ts
  packages/schema/tests/api-key.spec.ts
  packages/schema/tests/variable.spec.ts
Labels: Review effort [1-5]: 2

#682 feat(platform): restructure workspace settings and user settings
  apps/platform/src/app/(main)/(settings)/[workspace]/settings/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/@billing/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/@profile/loading.tsx
  apps/platform/src/app/(main)/(settings)/settings/@profile/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/layout.tsx
  apps/platform/src/app/(main)/settings/@workspace/page.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/shared/sidebar/sidebarTab/index.tsx
Labels: Review effort [1-5]: 4
