Repository keyshade-xyz/keyshade, pull requests merged in 2025-08, with the labels that each got.

#1099 fix(platform): update variable list after add or delete issue
  apps/platform/src/components/dashboard/variable/addVariableDialogue/index.tsx
  apps/platform/src/components/dashboard/variable/confirmDeleteVariable/index.tsx
  apps/platform/src/components/dashboard/variable/variableList/index.tsx
Labels: Review effort 2/5

#1100 fix(platform): corner radius in wrong place for secret and variable
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
Labels: Review effort 1/5

#1104 fix(ui): Role Tab Member Status and Role Naming Issues (#1097)
  apps/api/src/workspace-role/workspace-role.service.ts
  apps/platform/src/components/roles/roleCard/index.tsx
  packages/schema/src/workspace-role/index.ts
Labels: Review effort 2/5

#1107 fix(platform): add missing closing brace & update integration name casing
  apps/platform/src/components/integrations/createIntegration/index.tsx
Labels: Review effort 1/5

#1110 feat(docs): Changed contributing.md
  CONTRIBUTING.md
Labels: Review effort 1/5

#1075 feat(cli): request and response validation for `environment` commands
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/environment/create.environment.ts
  apps/cli/src/commands/environment/delete.environment.ts
  apps/cli/src/commands/environment/get.environment.ts
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/environment/update.environment.ts
  apps/cli/tsconfig.json
  packages/schema/package.json
  packages/schema/src/environment/index.ts
  packages/schema/src/pagination/index.ts
Labels: Review effort 2/5

#1127 fix(platform): adjust margin for sidebar component
  apps/platform/src/components/shared/sidebar/index.tsx
Labels: Review effort 1/5

#1129 fix: center align workspace name and icon
  apps/platform/src/app/(main)/(settings)/[workspace]/settings/page.tsx
Labels: Review effort 1/5

#1109 feat(api): added init function for discord integration
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/integration/plugins/discord.integration.ts
Labels: Review effort 3/5

#1132 fix(platform): Platform UI fixes
  apps/platform/package.json
  apps/platform/src/app/(main)/(settings)/settings/@billing/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/layout.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/shared/navbar/profile-menu.tsx
  apps/platform/src/components/shared/sidebar/tierLimit/index.tsx
  apps/platform/src/components/ui/infinite-scroll-list.tsx
  apps/platform/src/constants/navbar/tab-config.tsx
  apps/platform/src/hooks/api/use-create-new-project.ts
  apps/platform/src/hooks/api/use-get-all-projects.ts
  apps/platform/src/middleware.ts
  apps/platform/src/store/index.ts
  pnpm-lock.yaml
Labels: Review effort 2/5
