Repository keyshade-xyz/keyshade, pull requests merged in 2025-09, with the labels that each got.

#1139 feat: add book a demo
  apps/web/src/components/shared/navbar/index.tsx
Labels: Review effort 1/5

#1089 feat(api): Update init function of slack integration
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/integration/plugins/slack.integration.ts
Labels: Review effort 2/5

#1141 fix(platform): project icon alignment issue on dashboard
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
Labels: Review effort 1/5

#1146 chore(scoop): update to 2.34.0-stage.13
  bucket/keyshade.json
Labels: Review effort 1/5

#1148 chore(scoop): update to 2.34.0-stage.13
  bucket/keyshade.json
Labels: Review effort 1/5

#1149 chore(scoop): update to 2.34.0-stage.13
  bucket/keyshade.json
Labels: Review effort 1/5

#1150 chore(scoop): update to 2.34.0-stage.13
  bucket/keyshade.json
Labels: Review effort 1/5

#1151 chore(scoop): update to 2.34.0-stage.13
  bucket/keyshade.json
Labels: Review effort 1/5

#1111 feat(platform): implement drag and drop approach for importing configs
  apps/platform/src/components/dashboard/overview/ModifyFileScan/index.tsx
  apps/platform/src/components/dashboard/overview/ScanEnvFile/index.tsx
Labels: Review effort 3/5

#1155 feat(cli): make init command dynamically fetch config
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/init.command.ts
  package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#1168 fix(platform): trigger count now displays correct number of triggers
  apps/platform/src/components/integrations/integrationList/index.tsx
Labels: Review effort 2/5
