Repository keyshade-xyz/keyshade, pull requests merged in 2025-04, with the labels that each got.

#839 fix(platform): Scrollbar issue
  apps/platform/src/components/dashboard/project/projectScreenLoader/index.tsx
Labels: Review effort 1/5

#844 feat(web): migrated from nextjs 13 to 15
  apps/platform/src/components/dashboard/project/projectScreenLoader/index.tsx
  apps/web/next-env.d.ts
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/src/app/layout.tsx
  apps/web/src/components/secretSection/index.tsx
  apps/web/src/components/ui/following-pointer.tsx
  apps/web/src/components/ui/moving-border.tsx
  pnpm-lock.yaml
Labels: Review effort 3/5

#855 feat(platform): Add role listing
  apps/api/src/common/sentry-exception.filter.ts
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/variable.service.ts
  apps/api/src/workspace-role/workspace-role.e2e.spec.ts
  apps/api/src/workspace-role/workspace-role.service.ts
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/common/avatar.tsx
  apps/platform/src/components/dashboard/variable/addVariableDialogue/index.tsx
  apps/platform/src/components/roles/createRolesDialog/index.tsx
  apps/platform/src/components/roles/roleListItem/index.tsx
  apps/platform/src/components/roles/rolesList/index.tsx
  apps/platform/src/components/ui/avatar.tsx
  apps/platform/src/store/index.ts
  packages/schema/src/workspace-role/index.ts
Labels: Review effort 3/5

#856 feat(platform): Delete role functionality
  apps/api/src/common/sentry-exception.filter.ts
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/roles/confirmDeleteRole/index.tsx
  apps/platform/src/components/roles/createRolesDialog/index.tsx
  apps/platform/src/components/roles/roleCard/index.tsx
  apps/platform/src/components/roles/rolesList/index.tsx
  apps/platform/src/hooks/use-http.ts
  apps/platform/src/store/index.ts
Labels: Review effort 3/5

#854 feat(cli): implement resend workspace invitation command
  apps/api/src/workspace-membership/workspace-membership.service.ts
  apps/cli/CHANGELOG.md
  apps/cli/src/commands/workspace/membership.workspace.ts
  apps/cli/src/commands/workspace/membership/resend-invitation.membership.ts
  docs/contributing-to-keyshade/environment-variables.md
Labels: Review effort 2/5

#843 feat(platform): Project overview tab
  apps/api/src/workspace/workspace.e2e.spec.ts
  apps/api/src/workspace/workspace.service.ts
  apps/platform/public/svg/dashboard/folder.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/lock.svg
  apps/platform/public/svg/shared/regenerate.svg
  apps/platform/public/svg/shared/tick-circle.svg
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@overview/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/components/dashboard/overview/LocalKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/RegenerateKeyDialog/index.tsx
  apps/platform/src/components/dashboard/overview/RegenerateKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/ServerKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/ServerKeySetupDialog/index.tsx
  apps/platform/src/components/dashboard/overview/SetupLocalKeyDialog/index.tsx
  apps/platform/src/components/dashboard/overview/confirmDeleteKey/index.tsx
  apps/platform/src/components/dashboard/overview/overviewLoader/index.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/projectCard/index.tsx
  apps/platform/src/components/dashboard/project/viewAndDownloadKeysDialog/index.tsx
  apps/platform/src/components/dashboard/secret/decryptSecret/index.tsx
  apps/platform/src/components/shared/dashboard/hidden-content.tsx
  apps/platform/src/components/shared/information-card.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/shared/warning-card.tsx
  apps/platform/src/components/ui/switch.tsx
  apps/platform/src/hooks/use-fetch-privatekey.ts
  apps/platform/src/store/index.ts
  packages/schema/src/project/index.ts
Labels: Review effort 3/5

#846 feat(platform): Members Tab
  apps/platform/public/svg/shared/close-circle.svg
  apps/platform/public/svg/shared/edit-2.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/medal-star.svg
  apps/platform/public/svg/shared/user-remove.svg
  apps/platform/src/app/(main)/members/page.tsx
  apps/platform/src/app/(main)/teams/page.tsx
  apps/platform/src/components/members/editMemberDialog/index.tsx
  apps/platform/src/components/members/membersHeader/index.tsx
  apps/platform/src/components/members/membersTable/index.tsx
  apps/platform/src/components/members/removeMemberDialog/index.tsx
  apps/platform/src/components/members/transferOwnershipDialog/index.tsx
  apps/platform/src/components/roles/roleCard/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/teams/teamHeader/index.tsx
  apps/platform/src/components/teams/teamTable/index.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 4/5

#860 chore(docker): add self-hosted Sentry support to docker-compose
  .env.example
  docker-compose.yml
Labels: Review effort 2/5

#862 feat(platform): Edit Roles
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/roles/createRoleDialog/index.tsx
  apps/platform/src/components/roles/createRolesDialog/index.tsx
  apps/platform/src/components/roles/editRoleSheet/index.tsx
  apps/platform/src/components/roles/projectEnvironmentSelector/index.tsx
  apps/platform/src/components/roles/roleCard/index.tsx
  apps/platform/src/components/roles/rolesList/index.tsx
Labels: Review effort 3/5

#864 feat: add welcome email template and update account login email service
  apps/api/src/mail/emails/welcome-email.tsx
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/user/user.service.ts
Labels: Review effort 2/5

#866 ci: add PNPM and build caching to speed up workflow
  .github/workflows/release.yml
Labels: Review effort 2/5

#870 refactor: update switch component styles for checked state
  apps/platform/src/components/ui/switch.tsx
Labels: Review effort 1/5

#834 feat(platform): updated search component
  apps/api/src/workspace/workspace.service.ts
  apps/platform/package.json
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/page.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/global.css
  apps/platform/src/components/dashboard/environment/environmentCard/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
  apps/platform/src/components/shared/navbar/searchModel/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/hooks/use-debounce.ts
  apps/platform/src/store/index.ts
  apps/web/next.config.ts
  packages/schema/src/workspace/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#869 feat(platform): Upgrade to Next 15.2.3
  apps/platform/.eslintrc.cjs
  apps/platform/next-env.d.ts
  apps/platform/next.config.ts
  apps/platform/package.json
  apps/platform/public/svg/dashboard/folderIcon.svg
  apps/platform/public/svg/dashboard/index.ts
  apps/platform/public/svg/shared/regenerate.svg
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/layout.tsx
  apps/platform/src/components/dashboard/overview/LocalKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/RegenerateKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/ServerKeySetup/index.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/viewAndDownloadKeysDialog/index.tsx
  apps/platform/src/components/dashboard/secret/decryptSecret/index.tsx
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/roles/createRoleDialog/index.tsx
  apps/platform/src/components/roles/roleCard/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/lib/decrypt.ts
  apps/platform/src/middleware.ts
  apps/platform/tsconfig.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#874 fix: ui improvements in profile and workspace settings
  apps/platform/package.json
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
  apps/platform/src/components/ui/avatar.tsx
  apps/platform/src/components/ui/emoji-picker.tsx
  apps/platform/src/components/userSettings/apiKeys/apiKeyCard/index.tsx
  apps/platform/src/components/userSettings/profile/generalSettings/index.tsx
  pnpm-lock.yaml
Labels: Review effort 2/5

#876 fix(sidebar): update label from BETA to ALPHA
  apps/platform/src/components/shared/sidebar/index.tsx
Labels: Review effort 1/5

#877 fix(navbar): update keyboard shortcut display to include '+' for users
  apps/platform/src/components/shared/navbar/index.tsx
Labels: Review effort 1/5

#878 feat(layout): add TopBanner component for alpha launch
  apps/web/src/app/(main)/layout.tsx
  apps/web/src/components/topBanner/index.tsx
Labels: Review effort 1/5

#880 fix(docker): update next.config file extension from mjs to ts
  apps/web/Dockerfile
Labels: Review effort 1/5

#882 feat(cli): Add commands to update keyshade.json and private keys
  .env.example
  .github/workflows/release.yml
  apps/cli/CHANGELOG.md
  apps/cli/package-lock.json
  apps/cli/package.json
  apps/cli/src/commands/config.command.ts
  apps/cli/src/commands/config/private-key.config.ts
  apps/cli/src/commands/config/private-key/add.private-key.ts
  apps/cli/src/commands/config/private-key/delete.private-key.ts
  apps/cli/src/commands/config/private-key/list.private-key.ts
  apps/cli/src/commands/config/private-key/update.private-key.ts
  apps/cli/src/commands/config/update.config.ts
  apps/cli/src/commands/init.command.ts
  apps/cli/src/commands/profile/create.profile.ts
  apps/cli/src/commands/run.command.ts
  apps/cli/src/index.ts
  apps/cli/src/util/configuration.ts
  apps/cli/src/util/constants.ts
Labels: Review effort 3/5

#881 fix: update command group headings to uppercase and adjust text color
  apps/platform/src/components/shared/navbar/searchModel/index.tsx
Labels: Review effort 1/5

#883 fix(platform): Multiple API calls During add workspace
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/layout.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/components/shared/add-workspace-dialog.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/ui/infinite-scroll-list.tsx
Labels: Review effort 2/5

#884 fix(platform): UseEffectEvent Build error fix
  apps/platform/next.config.ts
  apps/platform/stubs/use-effect-event.js
Labels: Review effort 2/5

#891 feat: added PageTitle component and update page titles across the app
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@environment/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@overview/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
  apps/platform/src/app/(main)/members/page.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/app/(main)/roles/page.tsx
  apps/platform/src/components/common/page-title.tsx
Labels: Review effort 2/5

#893 fix(platform): roles tab breaking
  apps/platform/src/components/common/avatar.tsx
  apps/platform/src/components/roles/roleCard/index.tsx
Labels: Review effort 2/5

#896 fix(platform): Close search model after selecting a link
  apps/platform/src/components/shared/navbar/searchModel/index.tsx
Labels: Review effort 1/5

#892 feat(platform): Implementing InfiniteScroll To memberTab
  apps/platform/src/app/(main)/members/page.tsx
  apps/platform/src/components/members/membersTable/index.tsx
  apps/platform/src/components/ui/infinite-scroll-list.tsx
Labels: Review effort 2/5

#897 feat: add workspace invitations management and update UI
  apps/api/src/workspace/workspace.e2e.spec.ts
  apps/api/src/workspace/workspace.service.ts
  apps/platform/src/app/(main)/(settings)/settings/@invites/page.tsx
  apps/platform/src/app/(main)/(settings)/settings/layout.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/userSettings/workspace/inviteCard/index.tsx
  packages/schema/src/workspace/index.ts
Labels: Review effort 2/5

#900 feat(platform): Show Tier Limits
  apps/platform/package.json
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/layout.tsx
  apps/platform/src/components/dashboard/environment/addEnvironmentDialogue/index.tsx
  apps/platform/src/components/dashboard/environment/confirmDeleteEnvironment/index.tsx
  apps/platform/src/components/dashboard/project/confirmDeleteProject/index.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/secret/addSecretDialogue/index.tsx
  apps/platform/src/components/dashboard/secret/confirmDeleteSecret/index.tsx
  apps/platform/src/components/dashboard/variable/addVariableDialogue/index.tsx
  apps/platform/src/components/dashboard/variable/confirmDeleteVariable/index.tsx
  apps/platform/src/components/members/membersHeader/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/shared/sidebar/tierLimit/index.tsx
  apps/platform/src/components/ui/progress.tsx
  apps/platform/src/store/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#901 feat(platform): Platform Build Fix
  apps/platform/src/components/shared/sidebar/tierLimit/index.tsx
Labels: Review effort 2/5

#903 feat(web): Removing Pricing page from Web navbar
  apps/web/src/app/(main)/pricing/page.tsx
  apps/web/src/components/shared/navbar/index.tsx
Labels: Review effort 1/5

#902 fix(platform): Removed "People Invited" section from "Add Members" dialog
  CHANGELOG.md
  apps/platform/src/components/members/membersHeader/index.tsx
  apps/platform/src/components/shared/navbar/searchModel/index.tsx
  apps/platform/src/store/index.ts
  pnpm-lock.yaml
Labels: Review effort 3/5

#910 feat(platform): CLI command suggestion on view and download key component
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/link.svg
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@overview/page.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/viewAndDownloadKeysDialog/index.tsx
  apps/platform/src/components/shared/dashboard/command-suggestion.tsx
Labels: Review effort 2/5

#908 fix(platform): Added tooltips and disabled deletion of workspace admin in members
  apps/platform/src/components/members/membersTable/index.tsx
Labels: Review effort 2/5

#918 feat(platform): updated searchbar UI
  apps/platform/public/svg/shared/arrowdown.svg
  apps/platform/public/svg/shared/arrowup.svg
  apps/platform/public/svg/shared/index.ts
  apps/platform/public/svg/shared/select.svg
  apps/platform/src/components/shared/add-workspace-dialog.tsx
  apps/platform/src/components/shared/navbar/searchModel/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/ui/command.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 2/5

#913 fix(api): fix email action url for accept workshop invitation
  apps/api/src/workspace-membership/workspace-membership.service.ts
  apps/platform/src/components/members/membersHeader/index.tsx
Labels: Review effort 2/5

#916 fix(platform): update edit role data handling
  apps/platform/src/components/roles/editRoleSheet/index.tsx
Labels: Review effort 1/5

#865 fix: added contacts redirection
  apps/web/src/components/shared/footer/index.tsx
Labels: Review effort 1/5

#915 fix: enhance workspace selection handling and local storage integration
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
  apps/platform/src/components/dashboard/workspace/confirmDeleteWorkspace/index.tsx
  apps/platform/src/components/ui/combobox.tsx
  apps/platform/src/components/ui/workspace-list-item.tsx
  apps/platform/src/store/workspace.ts
Labels: Review effort 2/5

#923 feat(platform): Member tab update joined-invited tab
  apps/platform/src/app/(main)/members/@invited/page.tsx
  apps/platform/src/app/(main)/members/@joined/page.tsx
  apps/platform/src/app/(main)/members/layout.tsx
  apps/platform/src/app/(main)/members/page.tsx
  apps/platform/src/components/members/cancelInvitationDialog/index.tsx
  apps/platform/src/components/members/editMemberDialog/index.tsx
  apps/platform/src/components/members/memberRow/index.tsx
  apps/platform/src/components/members/membersTable/index.tsx
  apps/platform/src/components/members/removeMemberDialog/index.tsx
  apps/platform/src/components/members/transferOwnershipDialog/index.tsx
  apps/platform/src/components/shared/navbar/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/store/index.ts
Labels: Review effort 3/5

#925 fix(platform): Leave workspace Tooltip fix
  CHANGELOG.md
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
Labels: Review effort 2/5

#924 fix(platform): update workspace logic to include slug and update navigation logic
  apps/platform/src/app/(main)/(settings)/[workspace]/page.tsx
Labels: Review effort 2/5
