Repository keyshade-xyz/keyshade, pull requests merged in 2025-07, with the labels that each got.

#1037 fix(cli): Crash on secret decryption due to missing private key
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/secret/revisions.secret.ts
Labels: Review effort 1/5

#1040 feat(cli): Revamp CLI outputs
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/environment/list.environment.ts
  apps/cli/src/commands/profile/list.profile.ts
  apps/cli/src/commands/project/import.project.ts
  apps/cli/src/commands/project/list.project.ts
  apps/cli/src/commands/secret/list.secret.ts
  apps/cli/src/commands/variable/list.variable.ts
  apps/cli/src/commands/workspace/list.workspace.ts
  apps/cli/src/util/logger.ts
  apps/cli/src/util/table.ts
Labels: Review effort 3/5

#1044 docs: Next.js Integration Guide Minor Changes
  blob/nextjs-guide-server-side-output.png
  docs/integration/frameworks/set-up-with-nextjs.md
Labels: Review effort 2/5

#1042 docs: Add Python Integration Guide
  blob/keyshade-python-run.png
  blob/py-guide-code-output.png
  blob/py-guide-code.png
  docs/SUMMARY.md
  docs/integration/languages/set-up-with-python.md
Labels: Review effort 2/5

#1045 feat(platform): Updated Project Overview & Import from env files
  apps/platform/package.json
  apps/platform/public/svg/shared/regenerate.svg
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@overview/page.tsx
  apps/platform/src/components/dashboard/overview/AboutKeyshade/index.tsx
  apps/platform/src/components/dashboard/overview/ConfigAccessLevel/index.tsx
  apps/platform/src/components/dashboard/overview/ImportConfiguration/index.tsx
  apps/platform/src/components/dashboard/overview/ImportEnv/index.tsx
  apps/platform/src/components/dashboard/overview/LocalKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/ModifyFileScan/index.tsx
  apps/platform/src/components/dashboard/overview/ProjectDetails/index.tsx
  apps/platform/src/components/dashboard/overview/RegenerateKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/ScanEnvFile/index.tsx
  apps/platform/src/components/dashboard/overview/ServerKeySetup/index.tsx
  apps/platform/src/components/dashboard/overview/uploadEnvFile/index.tsx
  apps/platform/src/components/shared/sidebar/index.tsx
  apps/platform/src/components/ui/radio-group.tsx
  pnpm-lock.yaml
Labels: Possible security concern, Review effort 4/5

#1048 fix(platform): docker build fix
  apps/platform/package.json
  pnpm-lock.yaml
Labels: Possible security concern, Review effort 4/5

#1055 fix(api): Remove sensitive data logging in lambda integration
  apps/api/src/integration/plugins/aws-lambda.integration.ts
Labels: Review effort 1/5

#1059 fix: update policy
  apps/web/src/app/(main)/(mdx)/privacy/page.mdx
  apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
Labels: Review effort 1/5

#1060 feat(web): Pricing page update
  apps/web/src/app/(main)/pricing/page.tsx
  apps/web/src/components/pricing/card/index.tsx
  apps/web/src/components/shared/navbar/index.tsx
  apps/web/src/constants/pricing.ts
  apps/web/src/types/pricing.ts
Labels: Review effort 2/5

#1062 fix(web): Pricing page update
  apps/web/src/app/(main)/pricing/page.tsx
  apps/web/src/components/pricing/card/index.tsx
  apps/web/src/constants/pricing.ts
  apps/web/src/types/pricing.ts
Labels: Review effort 2/5

#1054 feat(api): add bulk upload support for secrets and variables
  apps/api/src/secret/dto/bulk.create.secret/bulk.create.secret.spec.ts
  apps/api/src/secret/dto/bulk.create.secret/bulk.create.secret.ts
  apps/api/src/secret/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/dto/bulk.create.variable/bulk.create.variable.spec.ts
  apps/api/src/variable/dto/bulk.create.variable/bulk.create.variable.ts
  apps/api/src/variable/variable.controller.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/variable/variable.service.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/variable.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
Labels: Review effort 2/5

#1066 fix(platform): Vercel integration was created using wrong environment metadata
  apps/api/src/integration/integration.types.ts
  apps/platform/src/components/integrations/ProjectEnvironmentMapping/index.tsx
  packages/common/src/integration.ts
Labels: Review effort 2/5

#1067 fix: API e2e test & store private key loaclly
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/platform/src/components/shared/dashboard/hidden-content.tsx
Labels: Review effort 2/5

#1071 docs: Integration Dropdown Pages README.md Created
  docs/SUMMARY.md
  docs/integration/frameworks/README.md
  docs/integration/languages/README.md
  docs/integration/platforms/README.md
Labels: Review effort 1/5

#1070 refactor(platform): Housekeeping
  apps/platform/src/app/(main)/layout.tsx
  apps/platform/src/app/(main)/page.tsx
  apps/platform/src/components/common/visible.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/create-project-access-level.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/create-project-description.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/create-project-environment-list.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/create-project-name.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/create-project-store-private-key.tsx
  apps/platform/src/components/dashboard/project/createProjectDialogue/index.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/export-project-environment-input.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/export-project-format-input.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/export-project-private-key-input.tsx
  apps/platform/src/components/dashboard/project/exportProjectConfigurations/index.tsx
  apps/platform/src/components/dashboard/project/viewAndDownloadKeysDialog/index.tsx
  apps/platform/src/components/main/ProjectEmpty/index.tsx
  apps/platform/src/components/main/ProjectLoader/index.tsx
  apps/platform/src/components/main/emptyProjectState/index.tsx
  apps/platform/src/components/ui/checkbox.tsx
  apps/platform/src/hooks/api/use-create-new-project.ts
  apps/platform/src/hooks/api/use-get-all-projects.ts
  apps/platform/src/hooks/api/use-project-environments.ts
  apps/platform/src/hooks/screen/project/createProjectDialogue/use-project-create-data.ts
  apps/platform/src/hooks/screen/project/exportProjectConfigurations/use-export-project-configurations.ts
  apps/platform/src/hooks/screen/project/exportProjectConfigurations/use-export-project-dialog.ts
  apps/platform/src/hooks/screen/project/exportProjectConfigurations/use-export-project-form.ts
  apps/platform/src/lib/download-file.ts
  apps/platform/src/lib/with-loading.ts
Labels: Review effort 3/5

#1078 fix(platform): Updating Secret/Variable in One Environment Also Increments Version in Another
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@secret/page.tsx
  apps/platform/src/app/(main)/(project)/[workspace]/[project]/@variable/page.tsx
  apps/platform/src/components/dashboard/overview/ScanEnvFile/index.tsx
  apps/platform/src/components/dashboard/secret/editSecretSheet/index.tsx
  apps/platform/src/components/dashboard/secret/secretLists/index.tsx
  apps/platform/src/components/dashboard/variable/editVariableSheet/index.tsx
  apps/platform/src/components/dashboard/variable/variableList/index.tsx
  apps/platform/src/components/ui/infinite-scroll-list.tsx
  apps/platform/src/hooks/use-highlight.ts
Labels: Review effort 3/5

#1086 fix(api): Vercel integration won't auto reload after configs are changes/added/deleted
  apps/api/src/integration/plugins/vercel.integration.ts
Labels: Review effort 2/5

#1050 feat: add feature to "disable" a certain configuration
  apps/api/src/prisma/migrations/20250711173652_add_disabled_tables/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/secret/secret.controller.ts
  apps/api/src/secret/secret.e2e.spec.ts
  apps/api/src/secret/secret.service.ts
  apps/api/src/variable/variable.controller.ts
  apps/api/src/variable/variable.e2e.spec.ts
  apps/api/src/variable/variable.service.ts
  apps/cli/src/commands/secret.command.ts
  apps/cli/src/commands/secret/disable.secret.ts
  apps/cli/src/commands/secret/enable.secret.ts
  apps/cli/src/commands/variable.command.ts
  apps/cli/src/commands/variable/disable.variable.ts
  apps/cli/src/commands/variable/enable.variable.ts
  apps/platform/src/components/dashboard/secret/secretCard/index.tsx
  apps/platform/src/components/dashboard/variable/variableCard/index.tsx
  apps/platform/src/store/index.ts
  packages/api-client/src/controllers/secret.ts
  packages/api-client/src/controllers/variable.ts
  packages/schema/src/secret/index.ts
  packages/schema/src/secret/index.types.ts
  packages/schema/src/variable/index.ts
  packages/schema/src/variable/index.types.ts
Labels: Review effort 3/5

#1035 feat: integration configuration testing
  apps/api/jest.config.ts
  apps/api/jest.e2e-config.ts
  apps/api/package.json
  apps/api/src/integration/dto/create.integration/create.integration.ts
  apps/api/src/integration/dto/update.integration/update.integration.ts
  apps/api/src/integration/integration.controller.ts
  apps/api/src/integration/integration.e2e.spec.ts
  apps/api/src/integration/integration.service.ts
  apps/api/src/integration/plugins/aws-lambda.integration.ts
  apps/api/src/integration/plugins/base.integration.ts
  apps/api/src/integration/plugins/discord.integration.ts
  apps/api/src/integration/plugins/slack.integration.ts
  apps/api/src/integration/plugins/vercel.integration.ts
  apps/platform/src/components/integrations/IntegrationDetails/index.tsx
  apps/platform/src/components/integrations/integrationSetup/index.tsx
  apps/platform/src/components/integrations/updateIntegrationSheet/index.tsx
  apps/platform/src/hooks/use-integration.ts
  apps/platform/src/store/index.ts
  packages/api-client/src/controllers/integration.ts
  packages/schema/src/integration/index.ts
  packages/schema/src/integration/index.types.ts
  pnpm-lock.yaml
Labels: Review effort 4/5

#1087 fix(api, cli): ambiguous error messages on keyshade run failure
  apps/api/src/socket/change-notifier.socket.ts
  apps/cli/CHANGELOG.md
  apps/cli/package.json
  apps/cli/src/commands/run.command.ts
  apps/cli/src/types/command/run.types.d.ts
Labels: Review effort 3/5

#1090 feat: Unfinished On-boarding Follow-up E-mail
  apps/api/src/mail/emails/onboarding-reminder-email-1.tsx
  apps/api/src/mail/emails/onboarding-reminder-email-2.tsx
  apps/api/src/mail/emails/onboarding-reminder-email-3.tsx
  apps/api/src/mail/emails/onboarding-reminder-email-4.tsx
  apps/api/src/mail/emails/onboarding-reminder-email-5.tsx
  apps/api/src/mail/emails/onboarding-reminder-email-6.tsx
  apps/api/src/mail/services/interface.service.ts
  apps/api/src/mail/services/mail.service.ts
  apps/api/src/mail/services/mock.service.ts
  apps/api/src/prisma/migrations/20250729154900_add_no_of_reminder_sent/migration.sql
  apps/api/src/prisma/migrations/20250730090929_rename_column/migration.sql
  apps/api/src/prisma/schema.prisma
  apps/api/src/user/user.service.ts
  pnpm-lock.yaml
Labels: Review effort 3/5
